"use client";
import { useState, useEffect } from "react";
import Link from "next/link";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import InquiryModal from "@/components/ui/InquiryModal";
import TableOfContents from "@/components/blog/TableOfContents";
import Comments from "@/components/blog/Comments";
import DestinationGallery from "@/components/blog/DestinationGallery";
import AffiliateBlock from "@/components/blog/AffiliateBlock";
import SmartImage from "@/components/ui/SmartImage";

const TOC=[{id:"honest",emoji:"⚡",label:"What Jibhi Actually Is"},{id:"season",emoji:"🌡️",label:"Best Time"},{id:"howtoreach",emoji:"🚌",label:"Getting There"},{id:"itinerary",emoji:"📅",label:"4-Day Itinerary"},{id:"places",emoji:"📍",label:"Key Places"},{id:"budget",emoji:"💰",label:"Budget"},{id:"tips",emoji:"💡",label:"Pro Tips"},{id:"faq",emoji:"❓",label:"FAQ"}];

function RP(){const[p,setP]=useState(0);useEffect(()=>{const u=()=>{const e=document.documentElement;setP(Math.min(100,(e.scrollTop/(e.scrollHeight-e.clientHeight))*100))};window.addEventListener("scroll",u,{passive:true});return()=>window.removeEventListener("scroll",u)},[]);return<div className="fixed top-0 left-0 right-0 z-[300] h-1 bg-parchment-2"><div className="h-full bg-emerald-500 transition-all duration-100" style={{width:`${p}%`}}/></div>}
function FAQ({q,a}:{q:string;a:string}){const[o,setO]=useState(false);return<div className="border border-parchment-2 rounded-xl overflow-hidden bg-white"><button onClick={()=>setO(!o)} className="w-full flex items-center justify-between px-5 py-4 text-left hover:bg-parchment transition-colors"><span className="font-medium text-sm text-ink pr-4">{q}</span><span className={`text-emerald-600 text-lg flex-shrink-0 transition-transform duration-200 ${o?"rotate-45":""}`}>+</span></button>{o&&<div className="px-5 pb-5 pt-1 border-t border-parchment-2"><p className="text-sm text-muted font-light leading-relaxed">{a}</p></div>}</div>}
function D({day,title,items,cost}:{day:string;title:string;items:string[];cost:string}){const[o,setO]=useState(true);return<div className="bg-white rounded-xl border border-parchment-2 overflow-hidden mb-4"><button onClick={()=>setO(!o)} className="w-full flex items-center justify-between px-5 py-4 bg-parchment hover:bg-parchment-2 transition-colors"><div className="flex items-center gap-3"><span className="font-serif text-xl text-emerald-600 font-light">{day}</span><span className="text-sm text-ink font-medium">{title}</span></div><span className="text-muted text-lg">{o?"−":"+"}</span></button>{o&&<div className="p-5"><ul className="space-y-2.5 mb-4">{items.map((item,i)=><li key={i} className="flex items-start gap-2.5 text-sm text-muted font-light leading-relaxed"><span className="text-emerald-500 mt-1 flex-shrink-0 text-xs">●</span>{item}</li>)}</ul><div className="pt-3 border-t border-parchment-2"><span className="text-xs text-muted font-light">Est. cost: </span><span className="text-xs font-medium text-emerald-600">{cost}</span></div></div>}</div>}

export default function JibhiClient(){
  const[m,setM]=useState(false);
  return<>
    <RP/><TableOfContents items={TOC}/><Navbar onPlanTrip={()=>setM(true)}/>
    <main className="bg-cream min-h-screen">
      <div className="relative h-[60vh] min-h-[420px] overflow-hidden">
        <SmartImage imageKey="jibhiHero" fallback="https://images.unsplash.com/photo-1585087905632-6e3af9e60baf?w=1600&q=85" alt="Jibhi Tirthan Valley Himachal Pradesh hidden village" fill className="object-cover" priority sizes="100vw" />
        <div className="absolute inset-0 bg-gradient-to-t from-ink/95 via-ink/50 to-ink/30"/>
        <div className="absolute top-24 left-0 right-0 px-6 md:px-14"><div className="max-w-[860px] mx-auto flex items-center gap-2 text-white/50 text-xs"><Link href="/" className="hover:text-gold transition-colors">Home</Link><span>/</span><Link href="/blog" className="hover:text-gold transition-colors">Blog</Link><span>/</span><span className="text-white/70">Jibhi & Tirthan Valley</span></div></div>
        <div className="absolute bottom-0 left-0 right-0 px-6 md:px-14 pb-10"><div className="max-w-[860px] mx-auto">
          <div className="flex items-center gap-3 mb-4 flex-wrap"><span className="bg-emerald-700 text-white text-[0.62rem] tracking-[0.12em] uppercase font-medium px-3 py-1.5 rounded-full">Himachal&apos;s Best Kept Secret</span><span className="text-white/60 text-xs">March 2026</span><span className="text-white/30">·</span><span className="text-white/60 text-xs">10 min read</span></div>
          <h1 className="font-serif text-[clamp(1.9rem,4.5vw,3.2rem)] font-light text-white leading-[1.08] mb-4">Jibhi & Tirthan Valley in 4 Days:<em className="italic text-emerald-300"> Himachal&apos;s Hidden Gem</em></h1>
          <p className="text-white/65 text-sm font-light max-w-[560px] leading-relaxed">Jalori Pass, Serolsar Lake, the Great Himalayan National Park and trout fishing in the Tirthan River. The most peaceful place in Himachal — before everyone finds out about it.</p>
        </div></div>
      </div>

      <div className="max-w-[860px] mx-auto px-6 md:px-8 pt-10 pb-20">
        <div className="flex items-center gap-4 text-xs text-muted mb-10 pb-8 border-b border-parchment-2"><span>🏡 Himachal Pradesh</span><span>·</span><span>🗓 4 Days</span><span>·</span><span>💰 From ₹5,000</span></div>

        <section id="honest" className="mb-14">
          <h2 className="font-serif text-[1.9rem] font-light text-ink mb-4">⚡ What Jibhi Actually Is</h2>
          <blockquote className="border-l-4 border-emerald-500 pl-6 mb-6 bg-emerald-50 rounded-r-xl py-4 pr-4"><p className="font-serif text-[1.05rem] italic text-ink-mid leading-relaxed">Jibhi is what Kasol was 10 years ago. A tiny village in the Tirthan Valley with apple orchards, traditional wooden houses and the Tirthan River running cold and clear past your guesthouse window. It&apos;s trending hard on Instagram — but most tourists still don&apos;t know how to get here.</p></blockquote>
          <p className="text-sm text-muted font-light leading-relaxed mb-4">The Tirthan Valley sits in the Great Himalayan National Park buffer zone — which means extraordinary birding, trout fishing and forest walks with zero crowds. Jalori Pass (3,120m) is just 8km from Jibhi village and accessible by road, making it one of the easiest high-altitude passes in Himachal. From the pass, a 5km walk takes you to Serolsar Lake — a sacred alpine lake in a dense deodar forest.</p>
          <p className="text-sm text-muted font-light leading-relaxed mb-6">Stay in a traditional wooden homestay. The food is extraordinary — trout pulled from the river that morning, local rajma, wild mushroom dishes. This is the Himachal that existed before tour operators got involved.</p>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3">{[{icon:"🚗",val:"510km",label:"From Delhi"},{icon:"🌡️",val:"Apr–Jun, Sep–Nov",label:"Best season"},{icon:"🏔️",val:"3,120m",label:"Jalori Pass"},{icon:"💰",val:"₹5,000+",label:"Budget from"}].map(s=><div key={s.label} className="bg-white rounded-xl border border-parchment-2 p-4 text-center"><div className="text-2xl mb-1">{s.icon}</div><p className="font-serif text-base font-light text-ink">{s.val}</p><p className="text-[0.65rem] text-muted uppercase tracking-wide mt-0.5">{s.label}</p></div>)}</div>
        </section>

        <section id="season" className="mb-14">
          <h2 className="font-serif text-[1.9rem] font-light text-ink mb-6">🌡️ Best Time to Visit</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
            {[{s:"Apr–Jun",i:"🌸",t:"Spring — Rhododendron Season",d:"Apple blossoms, rhododendrons in flower, Jalori Pass snow-capped but accessible. 10–22°C. Best for photography and birding. Most popular.",b:"Recommended",c:"bg-green-50 border-green-200"},{s:"Sep–Nov",i:"🍁",t:"Autumn — Apple Harvest",d:"Apple orchards golden, clear mountain views, crisp air 5–18°C. October is the most beautiful month. Much fewer tourists than spring.",b:"Best for peace",c:"bg-amber-50 border-amber-200"},{s:"Dec–Mar",i:"❄️",t:"Winter — Snow Season",d:"Heavy snow, Jalori Pass closed. Jibhi village accessible but cold (-5 to 10°C). Extraordinary if you want complete isolation.",b:"For snow lovers",c:"bg-blue-50 border-blue-200"},{s:"Jul–Aug",i:"🌧️",t:"Monsoon — Leech Season",d:"Heavy rain, leeches on every trail, roads prone to landslides. Tirthan River floods. Not recommended.",b:"Avoid",c:"bg-red-50 border-red-200"}].map(s=><div key={s.s} className={`rounded-xl p-4 border ${s.c}`}><div className="flex items-center gap-2 mb-2"><span className="text-xl">{s.i}</span><div><p className="font-medium text-sm text-ink">{s.s} — {s.t}</p><p className="text-[0.65rem] font-medium text-teal">{s.b}</p></div></div><p className="text-xs text-muted font-light leading-relaxed">{s.d}</p></div>)}
          </div>
        </section>

        <section id="howtoreach" className="mb-14">
          <h2 className="font-serif text-[1.9rem] font-light text-ink mb-6">🚌 Getting to Jibhi</h2>
          <div className="bg-amber-50 border border-amber-200 rounded-xl p-4 mb-4"><p className="text-sm text-amber-800 font-light leading-relaxed"><strong className="font-medium">Important:</strong> Jibhi is not on any major bus route. The nearest big town is Aut (on the Manali highway), then a local bus or taxi 30km into the valley. Most people drive or take an overnight bus to Kullu/Bhuntar and taxi the rest.</p></div>
          <div className="space-y-3">
            {[{i:"🚗",t:"Drive from Delhi (best option)",d:"510km via Chandigarh → Shimla → Aut → Banjar → Jibhi. 10–12hrs. NH3 is straightforward to Aut, then 30km valley road to Jibhi. Stay overnight in Chandigarh/Bilaspur if needed.",b:"Most convenient",c:"bg-green-50 border-green-200"},{i:"🚌",t:"Overnight bus + taxi",d:"Delhi Kashmere Gate → Kullu/Bhuntar (overnight bus, Rs.600–Rs.1,200, 10–12hrs). Then local taxi Bhuntar → Jibhi (Rs.1,500–Rs.2,000, 1.5hrs). Or local bus to Banjar (Rs.60–Rs.80) + auto to Jibhi.",b:"Budget option",c:"bg-amber-50 border-amber-200"},{i:"🚌",t:"Via Manali",d:"If combining with Manali: Manali → Aut → Banjar → Jibhi (80km, 2.5hrs). A perfect 2-day detour from Manali before heading back to Delhi.",b:"Combo route",c:"bg-parchment border-parchment-2"}].map(t=><div key={t.t} className={`rounded-xl p-4 border ${t.c}`}><div className="flex items-start gap-3"><span className="text-2xl flex-shrink-0">{t.i}</span><div className="flex-1"><div className="flex items-center gap-2 mb-1 flex-wrap"><p className="font-semibold text-sm text-ink">{t.t}</p><span className="text-[0.62rem] bg-white/70 text-muted px-2.5 py-1 rounded-full border border-white/50">{t.b}</span></div><p className="text-xs text-muted font-light leading-relaxed">{t.d}</p></div></div></div>)}
          </div>
        </section>

        <section id="itinerary" className="mb-14">
          <h2 className="font-serif text-[1.9rem] font-light text-ink mb-6">📅 4-Day Itinerary</h2>
          <D day="Day 1" title="Arrive + Jibhi Village + Waterfall" cost="₹800–₹1,500" items={["Arrive Jibhi and check in to a wooden homestay — the traditional Himachali architecture with carved balconies and slate roofs. Jibhi Cottages, Tirthan Cottage or any family-run homestay (Rs.1,000–Rs.2,500/night including meals).","Walk Jibhi village — the ancient wooden temple complex in the village centre (free). Apple orchards all around. The sound of the Tirthan River is constant.","Afternoon: Jibhi Waterfall (1.5km trek from village, free). 30-foot waterfall in a narrow canyon. Very few tourists even in peak season.","Evening: trout dinner at your homestay — fish caught from the river that morning. The best meal in the Tirthan Valley. Rs.200–Rs.400.","Night sky at Jibhi is extraordinary — zero light pollution at 1,500m elevation. Milky Way visible from your balcony."]}/>
          <D day="Day 2" title="Jalori Pass + Serolsar Lake Trek" cost="₹500–₹1,000" items={["Hire a local taxi to Jalori Pass (8km from Jibhi, Rs.500–Rs.700 return) or walk the 8km road in 2.5hrs. The pass at 3,120m has a small temple and extraordinary 360° mountain views.","Trek Jalori Pass → Serolsar Lake (5km each way, 2.5hrs each way). Dense deodar forest trail — almost completely flat. The lake at 3,100m is a sacred Budhi Nagin temple lake surrounded by ancient trees. Very few tourists.","Packed lunch from your homestay (ask the night before). Eat at the lake — snow-capped peaks above, deodar forest all around, complete silence.","Return to Jibhi by evening. Total day distance: ~10km walking + drive. Doable for moderate fitness levels."]}/>
          <D day="Day 3" title="GHNP Trek + Trout Fishing + Depart" cost="₹600–₹1,200" items={["Morning: Great Himalayan National Park buffer zone walk (entry Rs.50–Rs.100). The forest walk from Gushaini village (5km from Jibhi) follows the Tirthan River. Extraordinary birding — Western Tragopan, Himalayan Monal, Malabar Whistling Thrush.","Trout fishing on the Tirthan River — license from the fishery department (Rs.200–Rs.300/day). The Tirthan is one of India's best trout rivers. Your homestay host can usually arrange this and cook the fish for dinner.","Shopping before leaving: local honey (Rs.300–Rs.500/kg), home-made walnut jam, dried apricots. Significantly cheaper than anywhere else.","Drive/bus back to Delhi or continue to Manali (1.5hrs)."]}/>
        </section>

        <section id="places" className="mb-14">
          <h2 className="font-serif text-[1.9rem] font-light text-ink mb-6">📍 Key Places</h2>
          <div className="space-y-3">
            {[{n:"Serolsar Lake",e:"🏔️",d:"Sacred alpine lake at 3,100m surrounded by deodar and oak forest. 5km trek from Jalori Pass. The Budhi Nagin temple at the lake is considered sacred — remove shoes before entering. The reflection of the surrounding forest in the still water is extraordinary.",t:"5km trek from Jalori · 3hrs return"},{n:"Jalori Pass",e:"⛰️",d:"At 3,120m, this is one of the most accessible Himalayan passes — you can drive to within 1km of the top. The views of the Kullu Valley and Dhauladhar range on a clear day are extraordinary. Small Shringa Rishi temple at the summit.",t:"8km from Jibhi by road"},{n:"Great Himalayan National Park",e:"🦅",d:"UNESCO World Heritage Site. The buffer zone around Gushaini offers excellent day walks without requiring the expensive main park entry. Best birding in Himachal — especially the endangered Western Tragopan pheasant.",t:"5km from Jibhi · Forest entry Rs.50"},{n:"Tirthan River",e:"🎣",d:"The clearest river in Himachal Pradesh — you can see the rocks on the bottom at 3m depth. The best wild trout fishing in India, managed by the fishery department. Rainbow and brown trout.",t:"Flows through Jibhi village"}].map(place=><div key={place.n} className="bg-white rounded-xl border border-parchment-2 p-4 hover:border-emerald-300 transition-colors"><div className="flex items-center justify-between mb-2 flex-wrap gap-2"><div className="flex items-center gap-2"><span className="text-xl">{place.e}</span><p className="font-medium text-sm text-ink">{place.n}</p></div><span className="text-[0.65rem] bg-emerald-50 text-emerald-700 px-2.5 py-1 rounded-full border border-emerald-200">{place.t}</span></div><p className="text-xs text-muted font-light leading-relaxed">{place.d}</p></div>)}
          </div>
        </section>

        <section id="budget" className="mb-14">
          <h2 className="font-serif text-[1.9rem] font-light text-ink mb-6">💰 Budget Breakdown</h2>
          <div className="overflow-x-auto rounded-xl border border-parchment-2 shadow-sm">
            <table className="w-full text-sm"><thead><tr className="bg-parchment"><th className="text-left p-3.5 text-xs font-medium text-muted">Category</th><th className="p-3.5 text-xs font-medium text-amber-700 text-center">Budget</th><th className="p-3.5 text-xs font-medium text-emerald-700 text-center">Comfortable</th></tr></thead>
            <tbody className="divide-y divide-parchment-2">{[["🚗 Transport (Delhi return)","₹1,200–₹2,400","₹5,000–₹8,000"],["🏨 Homestay (2N, meals incl.)","₹2,000–₹4,000","₹4,000–₹8,000"],["🎯 Activities + Entry","₹800–₹1,200","₹1,200–₹2,000"],["🍽 Extra food","₹400–₹800","₹800–₹1,500"],["TOTAL per person","₹5,000–₹9,000","₹10,000–₹18,000"]].map(([cat,...vals])=><tr key={cat} className="bg-white hover:bg-parchment/40 transition-colors"><td className="p-3.5 text-xs text-ink font-medium">{cat}</td>{vals.map((v,i)=><td key={i} className="p-3.5 text-xs text-muted font-light text-center">{v}</td>)}</tr>)}</tbody></table>
          </div>
        </section>

        <AffiliateBlock destination="Jibhi Tirthan Valley Himachal Pradesh" hotels={[{name:"Tirthan Cottage",type:"Riverside homestay · Jibhi",price:"From ₹1,500/night",rating:"4",badge:"Best value",url:"https://www.booking.com/hotel/in/tirthan-cottage-jibhi.html?aid=YOUR_AFFILIATE_ID"},{name:"Jibhi Cottages",type:"Traditional wooden · Jibhi",price:"From ₹2,000/night",rating:"4",badge:"Most authentic",url:"https://www.booking.com/hotel/in/jibhi-cottages.html?aid=YOUR_AFFILIATE_ID"},{name:"White River Retreat",type:"Riverside resort · Tirthan",price:"From ₹4,000/night",rating:"4",badge:"Best views",url:"https://www.booking.com/hotel/in/white-river-retreat-tirthan.html?aid=YOUR_AFFILIATE_ID"},{name:"Tirthan Valley Homestay",type:"Family run · Gushaini",price:"From ₹1,200/night",rating:"4",badge:"GHNP access",url:"https://www.booking.com/hotel/in/tirthan-valley-homestay.html?aid=YOUR_AFFILIATE_ID"}]} activities={[{name:"Jalori Pass + Serolsar Lake Trek",duration:"Full day",price:"From ₹500/person",badge:"Must do",url:"https://www.getyourguide.com/kullu-l3011/?partner_id=PSZA5UI"},{name:"Tirthan River Trout Fishing",duration:"Half day",price:"From ₹300/person",badge:"Unique",url:"https://www.getyourguide.com/kullu-l3011/?partner_id=PSZA5UI"},{name:"GHNP Buffer Zone Forest Walk",duration:"3hrs",price:"From ₹200/person",url:"https://www.getyourguide.com/kullu-l3011/?partner_id=PSZA5UI"},{name:"Jibhi Waterfall + Village Walk",duration:"2hrs",price:"Free",url:"https://www.getyourguide.com/kullu-l3011/?partner_id=PSZA5UI"}]}/>

        <DestinationGallery title="Jibhi & Tirthan Valley" subtitle="Himachal's most peaceful hidden gem." spots={[{name:"Jalori Pass",query:"jalori pass himachal pradesh mountains snow pass trek",desc:"3,120m mountain pass accessible by road — panoramic Kullu and Dhauladhar views."},{name:"Serolsar Lake",query:"serolsar lake jalori pass deodar forest himachal",desc:"Sacred alpine lake surrounded by ancient deodar forest — 5km trek from Jalori Pass."},{name:"Tirthan River",query:"tirthan river clear water himachal pradesh trout fishing",desc:"The clearest river in Himachal — trout fishing on clear green water."},{name:"Jibhi Village",query:"jibhi village wooden houses himachal pradesh traditional",desc:"Traditional Himachali wooden houses with carved balconies in an apple orchard valley."},{name:"Great Himalayan National Park",query:"great himalayan national park wildlife forest himachal",desc:"UNESCO World Heritage forest — home to Western Tragopan and Himalayan Monal."}]}/>

        <section id="tips" className="mb-14">
          <h2 className="font-serif text-[1.9rem] font-light text-ink mb-6">💡 Pro Tips</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
            {[{i:"📵",t:"Download offline maps before leaving Aut",d:"Mobile network is almost non-existent in the Tirthan Valley — only BSNL works occasionally. Download Maps.me or Google Maps offline for the entire Kullu district before you enter.",c:"bg-amber-50 border-amber-200"},{i:"🎣",t:"Arrange trout fishing the evening before",d:"The fishery department office in Gushaini issues licenses (8am–4pm weekdays). Your homestay host can usually call ahead. Rs.200–Rs.300/day. Catch-and-release is mandatory in some stretches.",c:"bg-blue-50 border-blue-200"},{i:"🦅",t:"Best birding in India",d:"The Tirthan Valley has the highest bird diversity in Himachal. Western Tragopan (India's state bird), Khalij Pheasant and Himalayan Monal are commonly seen near Gushaini at dawn. Bring binoculars.",c:"bg-green-50 border-green-200"},{i:"🍎",t:"Buy apples directly from farms",d:"The valley is full of apple orchards. In September–October you can buy directly from farmers — Rs.20–Rs.40/kg vs Rs.80–Rs.120 in Delhi. Varieties you&apos;ve never tasted before.",c:"bg-rose-50 border-rose-200"},{i:"🏡",t:"Book homestays directly — not OTAs",d:"Most Jibhi homestays are family-run and list on OTAs with a 20–30% markup. Call or message directly (numbers on Google Maps). You&apos;ll pay less and they earn more.",c:"bg-purple-50 border-purple-200"},{i:"⚡",t:"Carry a power bank",d:"Power cuts happen daily in the valley — 2–4 hours is normal. The homestay will usually have candles/lanterns but your phone battery won&apos;t wait for the grid to come back.",c:"bg-teal-50 border-teal-200"}].map(t=><div key={t.t} className={`rounded-xl p-4 border ${t.c}`}><div className="flex items-start gap-3"><span className="text-xl flex-shrink-0">{t.i}</span><div><p className="font-medium text-sm text-ink mb-1">{t.t}</p><p className="text-xs text-muted font-light leading-relaxed">{t.d}</p></div></div></div>)}
          </div>
        </section>

        <div className="mb-14 bg-ink rounded-2xl p-8 text-center">
          <span className="text-[0.65rem] tracking-[0.2em] uppercase text-gold block mb-3">Free Service</span>
          <h2 className="font-serif text-[1.9rem] font-light text-white mb-3">Want Your Jibhi Trip Planned?</h2>
          <p className="text-sm text-white/55 font-light mb-7 max-w-[380px] mx-auto leading-relaxed">Tell us your dates and group size — personalised Tirthan Valley itinerary in 24 hours. Free.</p>
          <button onClick={()=>setM(true)} className="btn-gold">Plan My Trip →</button>
        </div>

        <section id="faq" className="mb-14">
          <h2 className="font-serif text-[1.9rem] font-light text-ink mb-6">❓ FAQ</h2>
          <div className="space-y-3">
            {[{q:"How to reach Jibhi from Delhi?",a:"510km via Chandigarh–Shimla–Aut–Banjar–Jibhi. Drive (10–12hrs) or overnight bus to Kullu/Bhuntar then taxi (Rs.1,500–Rs.2,000) to Jibhi."},{q:"What is Jibhi known for?",a:"Extreme peace and quiet, traditional Himachali wooden houses, trout fishing on the crystal Tirthan River, Jalori Pass (3,120m) 8km away, Serolsar Lake trek, and the Great Himalayan National Park buffer zone. Very few tourists."},{q:"Is Jibhi better than Kasol?",a:"Jibhi is more peaceful, less commercialised and has better trekking. Kasol is more social with cafes and a party vibe. Jibhi is for nature lovers and those who want to escape crowds. Kasol is for a lively backpacker scene."},{q:"Can I do Jibhi + Manali in one trip?",a:"Yes — perfectly. Jibhi → Manali is only 80km (2.5hrs via Aut). Do 2–4 days Jibhi then 2–4 days Manali — ideal 5–6 day Himachal circuit from Delhi."},{q:"Is Jalori Pass accessible in winter?",a:"Jalori Pass is closed by snow November–April. Jibhi village remains accessible year-round by road but the pass trek and Serolsar Lake are only possible May–October."}].map((item,i)=><FAQ key={i} {...item}/>)}
          </div>
        </section>
        <Comments/>
        <section className="mt-14"><h3 className="font-serif text-lg font-light text-ink mb-4">More Himachal Guides</h3>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">{[{label:"Manali 5 Days — Rohtang + Old Manali",href:"/blog/manali-5-days"},{label:"Spiti Valley 7 Days",href:"/blog/spiti-valley-7-days"},{label:"Leh Ladakh 7 Days",href:"/blog/leh-ladakh-7-days"},{label:"Kashmir 6 Days",href:"/blog/kashmir-6-days"}].map(link=><Link key={link.label} href={link.href} className="flex items-center justify-between p-4 bg-white rounded-lg border border-parchment-2 hover:border-gold hover:shadow-sm transition-all duration-200 group"><span className="text-sm text-ink font-light group-hover:text-teal transition-colors">{link.label}</span><span className="text-xs text-muted">Read →</span></Link>)}</div>
        </section>
      </div>
    </main>
    <Footer/><InquiryModal isOpen={m} onClose={()=>setM(false)}/>
  </>;
}
