// ─────────────────────────────────────────────────────────────────────────────
// SITE CONFIGURATION — edit this file to update your details everywhere
// ─────────────────────────────────────────────────────────────────────────────
import { blogPosts } from "@/data/blog";

export const SITE_CONFIG = {
  // ── Contact ────────────────────────────────────────────────────────────────
  email: "hello@incredibleitinerary.com",

  // ── Brand ──────────────────────────────────────────────────────────────────
  siteName: "IncredibleItinerary",
  tagline: "Curated Travel Guides Worldwide",
  siteUrl: "https://www.incredibleitinerary.com",

  // ── Social ─────────────────────────────────────────────────────────────────
  instagram: "https://instagram.com/incredibleitinerary",
  facebook:  "https://facebook.com/incredibleitinerary",
  youtube:   "https://youtube.com/@incredibleitinerary",

  // ── Business ───────────────────────────────────────────────────────────────
  foundedYear: "2024",
  guidesPublished: `${blogPosts.length}+`,
  responseTime: "24 hours",
};

// ── AFFILIATE LINKS ───────────────────────────────────────────────────────────
export const AFFILIATE = {
  // Booking.com affiliate — set NEXT_PUBLIC_BOOKING_AID in Vercel env vars
  bookingCom: (destination: string) => {
    const aid = process.env.NEXT_PUBLIC_BOOKING_AID;
    const base = `https://www.booking.com/search.html?ss=${encodeURIComponent(destination)}&lang=en-us`;
    return aid ? `${base}&aid=${aid}` : base;
  },

  // GetYourGuide — partner code: PSZA5UI ✅ LIVE
  getYourGuide: (destination: string) =>
    `https://www.getyourguide.com/s/?q=${encodeURIComponent(destination)}&partner_id=PSZA5UI`,

  // Viator — uses env var if set
  viator: (destination: string) => {
    const vid = process.env.NEXT_PUBLIC_VIATOR_ID;
    const base = `https://www.viator.com/search/${encodeURIComponent(destination)}`;
    return vid ? `${base}?mcid=${vid}` : base;
  },

  // Direct hotel links — set NEXT_PUBLIC_BOOKING_AID in Vercel env vars
  hotels: (() => {
    const aid = process.env.NEXT_PUBLIC_BOOKING_AID;
    const suffix = aid ? `?aid=${aid}` : "";
    return {
      zostelGoa:         `https://www.booking.com/hotel/in/zostel-goa.html${suffix}`,
      raasJodhpur:       `https://www.booking.com/hotel/in/raas-jodhpur.html${suffix}`,
      tajLakePalace:     `https://www.booking.com/hotel/in/taj-lake-palace-udaipur.html${suffix}`,
      rambaghPalace:     `https://www.booking.com/hotel/in/rambagh-palace-jaipur.html${suffix}`,
      ametHaveliUdaipur: `https://www.booking.com/hotel/in/amet-haveli-udaipur.html${suffix}`,
    };
  })(),

  // Activities — GetYourGuide with PSZA5UI ✅ LIVE
  activities: {
    goaHeritage:     "https://www.getyourguide.com/goa-l976/?partner_id=PSZA5UI",
    goaCruise:       "https://www.getyourguide.com/goa-l976/cruises/?partner_id=PSZA5UI",
    dudhsagarJeep:   "https://www.getyourguide.com/goa-l976/dudhsagar/?partner_id=PSZA5UI",
    amberFortTour:   "https://www.getyourguide.com/jaipur-l200/?partner_id=PSZA5UI",
    mehrangarhTour:  "https://www.getyourguide.com/jodhpur-l1435/?partner_id=PSZA5UI",
    jaisalmerDesert: "https://www.getyourguide.com/jaisalmer-l1436/?partner_id=PSZA5UI",
    udaipurBoat:     "https://www.getyourguide.com/udaipur-l1437/?partner_id=PSZA5UI",
    bishnoisafari:   "https://www.getyourguide.com/jodhpur-l1435/village-safari/?partner_id=PSZA5UI",
  },
};

// ── SHOP / PDF PRODUCTS ───────────────────────────────────────────────────────
// razorpayUrl: use the matching tier link from Razorpay dashboard
// ₹99 → rzp.io/rzp/8rDJsEUZ · ₹149 → rzp.io/rzp/NkTrlcV · ₹199 → rzp.io/rzp/qqRpbf9 · ₹249 → rzp.io/rzp/kU16tbV
export const SHOP_PRODUCTS = [
  {
    id: "goa-3-days-pdf",
    title: "Goa in 3 Days — Complete Itinerary PDF",
    subtitle: "4 plans · Day-by-day schedule · Budget tables · Google Maps routes · Pro tips",
    price: 99,
    originalPrice: 199,
    currency: "₹",
    pages: "28 pages",
    destination: "Goa",
    emoji: "🏖️",
    color: "border-teal-200 bg-teal-50",
    accent: "text-teal-700",
    includes: [
      "4 complete itineraries (Budget, Couple, Party, Relaxed)",
      "Day-by-day schedule with exact timings",
      "Budget breakdown tables — all plans",
      "Google Maps route links for every day",
      "17 restaurant recommendations with prices",
      "Mistakes to avoid + pro tips",
      "Packing list for Goa",
      "Best time to visit guide",
    ],
    razorpayUrl: "https://rzp.io/rzp/8rDJsEUZ",
    badge: "Bestseller",
  },
  {
    id: "rajasthan-7-days-pdf",
    title: "Rajasthan in 7 Days — Royal Circuit PDF",
    subtitle: "4 plans · Jaipur · Jodhpur · Jaisalmer · Udaipur · Full route guide",
    price: 149,
    originalPrice: 299,
    currency: "₹",
    pages: "42 pages",
    destination: "Rajasthan",
    emoji: "🏰",
    color: "border-amber-200 bg-amber-50",
    accent: "text-amber-700",
    includes: [
      "4 complete itineraries (Budget, Couple, Family, Luxury)",
      "Full circuit route: Jaipur → Jodhpur → Jaisalmer → Udaipur",
      "Entry fees, timings, and booking tips for every fort",
      "Best desert camp recommendations by budget",
      "Transport guide — train numbers, booking tips",
      "Palace hotel recommendations with real prices",
      "Shopping guide — what to buy and where",
      "Packing list for Rajasthan",
    ],
    razorpayUrl: "https://rzp.io/rzp/NkTrlcV",
    downloadSlug: "rajasthan-7-days",
    badge: "Most Detailed",
  },
  {
    id: "india-budget-guide-pdf",
    title: "India on a Budget — Complete Traveller's Guide",
    subtitle: "How to travel India for under ₹3,000/day · All regions covered",
    price: 99,
    originalPrice: 199,
    currency: "₹",
    pages: "18 pages",
    destination: "All India",
    emoji: "🇮🇳",
    color: "border-purple-200 bg-purple-50",
    accent: "text-purple-700",
    includes: [
      "Budget breakdown for 8 major destinations",
      "Best budget accommodation by city",
      "How to eat well for ₹150–₹300/day",
      "Train booking guide — apps, classes, tips",
      "Apps every India traveller needs",
      "Common scams and how to avoid them",
    ],
    razorpayUrl: "https://rzp.io/rzp/8rDJsEUZ",
    badge: "New",
  },
  {
    id: "kerala-5-days-pdf",
    title: "Kerala in 5 Days — Backwaters to Hills PDF",
    subtitle: "4 plans · Alleppey · Munnar · Kochi · Thekkady · Varkala",
    price: 149,
    originalPrice: 299,
    currency: "₹",
    pages: "36 pages",
    destination: "Kerala",
    emoji: "🌿",
    color: "border-green-200 bg-green-50",
    accent: "text-green-700",
    includes: [
      "4 complete itineraries (Budget, Couple, Family, Luxury)",
      "Backwaters houseboat booking guide with real prices",
      "Munnar tea estate trails and viewpoints",
      "Best Ayurveda resorts by budget",
      "Kochi heritage walk map + Fort Kochi guide",
      "Train & bus connections across Kerala",
      "Monsoon travel tips — what to expect",
      "Packing list for Kerala",
    ],
    razorpayUrl: "https://rzp.io/rzp/NkTrlcV",
    downloadSlug: "kerala-5-days",
    badge: "New",
  },
  {
    id: "leh-ladakh-7-days-pdf",
    title: "Leh Ladakh in 7 Days — Complete High Altitude Guide PDF",
    subtitle: "4 plans · Pangong Lake · Nubra Valley · Khardung La · Full circuit",
    price: 199,
    originalPrice: 399,
    currency: "₹",
    pages: "48 pages",
    destination: "Leh Ladakh",
    emoji: "🏔️",
    color: "border-blue-200 bg-blue-50",
    accent: "text-blue-700",
    includes: [
      "4 complete itineraries (Budget Biker, Couple, Solo, Family)",
      "Day-by-day acclimatisation schedule — avoid AMS",
      "Full permit guide — ILP, photography permits",
      "Pangong Lake — best camps by budget",
      "Nubra Valley — Bactrian camel dunes guide",
      "Bike rental guide — which bikes, what to check",
      "Emergency contacts + altitude sickness protocol",
      "Packing list for high altitude Ladakh",
    ],
    razorpayUrl: "https://rzp.io/rzp/qqRpbf9",
    badge: "Premium",
  },
  {
    id: "bangkok-4-days-pdf",
    title: "Bangkok in 4 Days — Complete Thailand Capital PDF",
    subtitle: "4 plans · Temples · Street food · Nightlife · Day trips",
    price: 199,
    originalPrice: 399,
    currency: "₹",
    pages: "32 pages",
    destination: "Bangkok",
    emoji: "🇹🇭",
    color: "border-yellow-200 bg-yellow-50",
    accent: "text-yellow-700",
    includes: [
      "4 complete itineraries (Budget, Couple, Party, Culture)",
      "Temple circuit with exact entry fees & opening times",
      "Street food map — 23 must-eat stalls with prices",
      "Chatuchak Weekend Market full guide",
      "Day trip options: Ayutthaya, Kanchanaburi, Pattaya",
      "BTS/MRT navigation guide + taxi tips",
      "SIM card + currency exchange guide for Indians",
      "Packing list for Bangkok heat",
    ],
    razorpayUrl: "https://rzp.io/rzp/qqRpbf9",
    badge: "International",
  },
  {
    id: "kashmir-6-days-pdf",
    title: "Kashmir in 6 Days — Heaven on Earth PDF",
    subtitle: "4 plans · Srinagar · Gulmarg · Pahalgam · Sonamarg",
    price: 149,
    originalPrice: 299,
    currency: "₹",
    pages: "36 pages",
    destination: "Kashmir",
    emoji: "❄️",
    color: "border-green-200 bg-green-50",
    accent: "text-green-700",
    includes: [
      "4 complete itineraries (Budget, Couple, Family, Luxury)",
      "Houseboat on Dal Lake — booking guide & real prices",
      "Gondola to Apharwat Peak 4200m — full guide",
      "Pahalgam & Sonamarg day-by-day plans",
      "Genuine Pashmina buying guide",
      "Safety tips & best time to visit",
      "Wazwan food guide — what to eat & where",
      "Packing list for Kashmir weather",
    ],
    razorpayUrl: "https://rzp.io/rzp/NkTrlcV",
    badge: "Popular",
  },
  {
    id: "manali-5-days-pdf",
    title: "Manali in 5 Days — Snow, Passes & Hills PDF",
    subtitle: "4 plans · Solang Valley · Rohtang Pass · Old Manali · Kasol",
    price: 149,
    originalPrice: 299,
    currency: "₹",
    pages: "32 pages",
    destination: "Manali",
    emoji: "⛰️",
    color: "border-purple-200 bg-purple-50",
    accent: "text-purple-700",
    includes: [
      "4 complete itineraries (Budget, Couple, Adventure, Family)",
      "Rohtang Pass permit guide — how to book online",
      "Solang Valley activities with exact prices",
      "Kheerganga trek guide — trail, camps, hot spring",
      "Old Manali café guide + best stays",
      "Bike rental guide — Royal Enfield tips",
      "Monsoon warning — when NOT to go",
      "Packing list for Himachal weather",
    ],
    razorpayUrl: "https://rzp.io/rzp/NkTrlcV",
    badge: "New",
  },
  {
    id: "bali-5-days-pdf",
    title: "Bali in 5 Days — Island of the Gods PDF",
    subtitle: "4 plans · Ubud · Seminyak · Uluwatu · Nusa Penida",
    price: 199,
    originalPrice: 399,
    currency: "₹",
    pages: "36 pages",
    destination: "Bali",
    emoji: "🌴",
    color: "border-emerald-200 bg-emerald-50",
    accent: "text-emerald-700",
    includes: [
      "4 complete itineraries (Budget, Couple, Luxury, Party)",
      "Visa on arrival guide for Indians (free since 2024)",
      "Ubud rice terraces, temples & Kecak fire dance",
      "Batur volcano sunrise trek — full guide",
      "Uluwatu & Seminyak beach club guide",
      "Nusa Penida day trip — Kelingking Beach & more",
      "Budget in ₹ and USD/IDR",
      "Grab app guide — avoid taxi scams",
    ],
    razorpayUrl: "https://rzp.io/rzp/qqRpbf9",
    badge: "International",
  },
  {
    id: "dubai-4-days-pdf",
    title: "Dubai in 4 Days — Gold, Glass & Desert PDF",
    subtitle: "4 plans · Downtown · Marina · Desert Safari · Deira",
    price: 249,
    originalPrice: 499,
    currency: "₹",
    pages: "36 pages",
    destination: "Dubai",
    emoji: "🏙️",
    color: "border-amber-200 bg-amber-50",
    accent: "text-amber-700",
    includes: [
      "4 complete itineraries (Budget, Couple, Luxury, Family)",
      "UAE visa guide for Indians — step by step",
      "Burj Khalifa — best tickets, when to book",
      "Gold Souk & Spice Souk bargaining guide",
      "Desert Safari — what to expect, best operators",
      "Metro + Nol card guide — save on transport",
      "Budget in ₹ and AED",
      "Ramadan etiquette & cultural tips",
    ],
    razorpayUrl: "https://rzp.io/rzp/kU16tbV",
    badge: "Premium",
  },
  // ── Phase 2 ───────────────────────────────────────────────────────────────
  {
    id: "andaman-5-days-pdf",
    title: "Andaman Islands in 5 Days — Beaches, Diving & History PDF",
    subtitle: "3 islands · Port Blair · Havelock · Neil Island · Scuba guide",
    price: 149,
    originalPrice: 299,
    currency: "₹",
    pages: "28 pages",
    destination: "Andaman",
    emoji: "🏝️",
    color: "border-cyan-200 bg-cyan-50",
    accent: "text-cyan-700",
    includes: [
      "3-island circuit: Port Blair → Havelock → Neil",
      "Ferry booking guide (Makruzz, Green Ocean)",
      "Radhanagar Beach + Elephant Beach snorkelling",
      "Scuba diving guide — best dive centres & prices",
      "Budget table (₹11,800–₹55,000 for 5 days)",
      "Cellular Jail + Ross Island history guide",
      "Cash & ATM survival guide for outer islands",
      "Packing list for island & beach travel",
    ],
    razorpayUrl: "https://rzp.io/rzp/NkTrlcV",
    badge: "New",
  },
  {
    id: "varanasi-3-days-pdf",
    title: "Varanasi in 3 Days — Ghats, Temples & Ganga Aarti PDF",
    subtitle: "Dashashwamedh · Kashi Vishwanath · Sarnath · Sunrise boat",
    price: 99,
    originalPrice: 199,
    currency: "₹",
    pages: "22 pages",
    destination: "Varanasi",
    emoji: "🕌",
    color: "border-orange-200 bg-orange-50",
    accent: "text-orange-700",
    includes: [
      "3-day spiritual circuit with exact timings",
      "Ganga Aarti guide — best spots & photography tips",
      "Kashi Vishwanath darshan — app booking guide",
      "Sunrise boat ride — best ghats & prices",
      "Sarnath day trip — Buddhist heritage",
      "Banarasi silk buying guide (real vs fake)",
      "Budget table (₹2,800–₹52,000 for 3 days)",
      "Scam warning + tips for first-timers",
    ],
    razorpayUrl: "https://rzp.io/rzp/8rDJsEUZ",
    badge: "New",
  },
  {
    id: "singapore-4-days-pdf",
    title: "Singapore in 4 Days — Marina Bay, Sentosa & Hawker Heaven PDF",
    subtitle: "4 plans · Gardens by the Bay · Sentosa · Little India · Orchard",
    price: 199,
    originalPrice: 399,
    currency: "₹",
    pages: "28 pages",
    destination: "Singapore",
    emoji: "🇸🇬",
    color: "border-red-200 bg-red-50",
    accent: "text-red-700",
    includes: [
      "4 complete itineraries (Budget, Couple, Family, Luxury)",
      "eVisa guide for Indians — step by step",
      "MRT navigation + EZ-Link card setup",
      "Hawker centre guide — Maxwell, Lau Pa Sat, Newton",
      "Universal Studios Singapore — skip-the-line tips",
      "Budget in ₹ and SGD",
      "Free things to do (Supertree show, Merlion, Haji Lane)",
      "Changi Airport — Jewel waterfall + transit tips",
    ],
    razorpayUrl: "https://rzp.io/rzp/qqRpbf9",
    badge: "International",
  },
  {
    id: "sri-lanka-7-days-pdf",
    title: "Sri Lanka in 7 Days — Kandy, Ella, Yala & Galle PDF",
    subtitle: "4 plans · Colombo · Kandy · Ella train · Yala safari · Galle fort",
    price: 199,
    originalPrice: 399,
    currency: "₹",
    pages: "32 pages",
    destination: "Sri Lanka",
    emoji: "🦁",
    color: "border-amber-200 bg-amber-50",
    accent: "text-amber-700",
    includes: [
      "Complete Colombo→Kandy→Ella→Yala→Galle loop",
      "Ella scenic train booking guide (12go.asia)",
      "Nine Arch Bridge + Little Adam's Peak hike",
      "Yala National Park leopard safari guide",
      "Indians: 30-day free visa on arrival details",
      "Budget in ₹ and LKR",
      "PickMe app guide (save 60% on taxis)",
      "Galle Dutch Fort + Mirissa whale watching",
    ],
    razorpayUrl: "https://rzp.io/rzp/qqRpbf9",
    badge: "New",
  },
  {
    id: "japan-10-days-pdf",
    title: "Japan in 10 Days — Tokyo, Kyoto, Osaka & Hiroshima PDF",
    subtitle: "Tokyo · Nikko · Kyoto · Nara · Osaka · Hiroshima · Miyajima",
    price: 299,
    originalPrice: 599,
    currency: "₹",
    pages: "40 pages",
    destination: "Japan",
    emoji: "🗼",
    color: "border-red-200 bg-red-50",
    accent: "text-red-700",
    includes: [
      "Complete 10-day Tokyo→Kyoto→Osaka circuit",
      "Japan visa guide for Indians — step by step",
      "JR Pass guide — buy in India, saves ₹15,000+",
      "Cherry blossom timing + booking guide",
      "Fushimi Inari, Arashiyama, TeamLab — full guides",
      "Budget in ₹ and JPY (₹78,500–₹3,60,500)",
      "Hawker & convenience store food guide",
      "Day-by-day 10-page reference summary",
    ],
    razorpayUrl: "https://rzp.io/rzp/kU16tbV",
    badge: "Premium",
  },
  // ── Phase 3 ───────────────────────────────────────────────────────────────
  {
    id: "vietnam-10-days-pdf",
    title: "Vietnam in 10 Days — Hanoi to Ho Chi Minh City PDF",
    subtitle: "Hanoi · Ha Long Bay · Hué · Hội An · Đà Nẵng · Saigon",
    price: 199,
    originalPrice: 399,
    currency: "₹",
    pages: "38 pages",
    destination: "Vietnam",
    emoji: "🇻🇳",
    color: "border-red-200 bg-red-50",
    accent: "text-red-700",
    includes: [
      "North→South or South→North routes",
      "E-visa guide for Indians (step by step)",
      "Ha Long Bay cruise — day vs overnight guide",
      "Hội An Ancient Town full guide",
      "Budget in ₹ and VND (₹50,000–₹2,50,000)",
      "Grab app + train booking guide",
      "Street food guide — bánh mì, phở, cơm tấm",
      "Best time to visit each region",
    ],
    razorpayUrl: "https://rzp.io/rzp/qqRpbf9",
    badge: "New",
  },
  {
    id: "thailand-10-days-pdf",
    title: "Thailand in 10 Days — Bangkok to Krabi PDF",
    subtitle: "Bangkok · Chiang Mai · Pai · Phuket · Phi Phi · Krabi",
    price: 199,
    originalPrice: 399,
    currency: "₹",
    pages: "36 pages",
    destination: "Thailand",
    emoji: "🌴",
    color: "border-amber-200 bg-amber-50",
    accent: "text-amber-700",
    includes: [
      "Bangkok + beach + mountains full circuit",
      "Visa-on-arrival guide for Indians (free since 2024)",
      "Island hopping — Phi Phi, Railay, James Bond",
      "Night markets + street food guide",
      "Budget in ₹ and THB (₹60,000–₹2,80,000)",
      "Songthaew + TukTuk + ferry guide",
      "Elephant sanctuary guide (ethical only)",
      "Best time to visit by region",
    ],
    razorpayUrl: "https://rzp.io/rzp/qqRpbf9",
    badge: "New",
  },
  {
    id: "bhutan-5-days-pdf",
    title: "Bhutan in 5 Days — Tiger's Nest & Beyond PDF",
    subtitle: "Paro · Thimphu · Punakha · Tiger's Nest hike · Dochula Pass",
    price: 199,
    originalPrice: 399,
    currency: "₹",
    pages: "28 pages",
    destination: "Bhutan",
    emoji: "🏔️",
    color: "border-orange-200 bg-orange-50",
    accent: "text-orange-700",
    includes: [
      "Indians: no visa required + SDF waiver details",
      "Tiger's Nest Monastery full hike guide",
      "Punakha Dzong & suspension bridge",
      "SDF fee explained (₹1,200/night for Indians)",
      "Budget in ₹ (₹35,000–₹1,80,000 for 5 days)",
      "Best time to visit + festival calendar",
      "Bhutanese cuisine guide",
      "Flight + taxi booking guide from India",
    ],
    razorpayUrl: "https://rzp.io/rzp/qqRpbf9",
    badge: "New",
  },
  {
    id: "portugal-7-days-pdf",
    title: "Portugal in 7 Days — Lisbon, Porto & Algarve PDF",
    subtitle: "Lisbon · Sintra · Porto · Douro Valley · Algarve coast",
    price: 249,
    originalPrice: 499,
    currency: "₹",
    pages: "34 pages",
    destination: "Portugal",
    emoji: "🇵🇹",
    color: "border-blue-200 bg-blue-50",
    accent: "text-blue-700",
    includes: [
      "Schengen visa guide for Indians — step by step",
      "Lisbon tram 28 + miradouros route",
      "Sintra palaces — which ones are worth it",
      "Porto wine cellar tours + Douro Valley",
      "Algarve caves, grottos & beach guide",
      "Budget in ₹ and EUR (₹95,000–₹4,00,000)",
      "TAP Air + train + bus connections",
      "Pastel de nata + bacalhau food guide",
    ],
    razorpayUrl: "https://rzp.io/rzp/kU16tbV",
    badge: "Premium",
  },
  {
    id: "greece-10-days-pdf",
    title: "Greece in 10 Days — Athens to Santorini PDF",
    subtitle: "Athens · Mykonos · Santorini · Crete · Rhodes · Delphi",
    price: 299,
    originalPrice: 599,
    currency: "₹",
    pages: "42 pages",
    destination: "Greece",
    emoji: "🇬🇷",
    color: "border-sky-200 bg-sky-50",
    accent: "text-sky-700",
    includes: [
      "Schengen visa guide for Indians",
      "Athens → island hopping ferry guide",
      "Santorini oia sunset — how to beat crowds",
      "Crete: Samaria Gorge + Balos beach",
      "Budget in ₹ and EUR (₹1,20,000–₹5,50,000)",
      "Greek island ferry booking (ferryscanner.com)",
      "Acropolis + museum skip-the-line tips",
      "Meze + seafood food guide by island",
    ],
    razorpayUrl: "https://rzp.io/rzp/kU16tbV",
    badge: "Premium",
  },
];


