"use client";
import { useState, useEffect } from "react";
import Link from "next/link";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import InquiryModal from "@/components/ui/InquiryModal";
import TableOfContents from "@/components/blog/TableOfContents";
import Comments from "@/components/blog/Comments";
import DestinationGallery from "@/components/blog/DestinationGallery";
import AffiliateBlock from "@/components/blog/AffiliateBlock";
import SmartImage from "@/components/ui/SmartImage";
import RelatedGuides from "@/components/blog/RelatedGuides";
import Breadcrumb from "@/components/blog/Breadcrumb";

const TOC=[{id:"honest",emoji:"⚡",label:"What Spiti Actually Is"},{id:"season",emoji:"🌡️",label:"When to Go"},{id:"howtoreach",emoji:"🚗",label:"Routes In"},{id:"itinerary",emoji:"📅",label:"7-Day Itinerary"},{id:"monasteries",emoji:"🕌",label:"Monastery Guide"},{id:"budget",emoji:"💰",label:"Budget"},{id:"tips",emoji:"💡",label:"Pro Tips"},{id:"faq",emoji:"❓",label:"FAQ"}];

function RP(){const[p,setP]=useState(0);useEffect(()=>{const u=()=>{const e=document.documentElement;setP(Math.min(100,(e.scrollTop/(e.scrollHeight-e.clientHeight))*100))};window.addEventListener("scroll",u,{passive:true});return()=>window.removeEventListener("scroll",u)},[]);return<div className="fixed top-0 left-0 right-0 z-[300] h-1 bg-parchment-2"><div className="h-full bg-slate-500 transition-all duration-100" style={{width:`${p}%`}}/></div>}
function FAQ({q,a}:{q:string;a:string}){const[o,setO]=useState(false);return<div className="border border-parchment-2 rounded-xl overflow-hidden bg-white"><button onClick={()=>setO(!o)} className="w-full flex items-center justify-between px-5 py-4 text-left hover:bg-parchment transition-colors"><span className="font-medium text-sm text-ink pr-4">{q}</span><span className={`text-slate-500 text-lg flex-shrink-0 transition-transform duration-200 ${o?"rotate-45":""}`}>+</span></button>{o&&<div className="px-5 pb-5 pt-1 border-t border-parchment-2"><p className="text-sm text-muted font-light leading-relaxed">{a}</p></div>}</div>}
function D({day,title,items,cost}:{day:string;title:string;items:string[];cost:string}){const[o,setO]=useState(true);return<div className="bg-white rounded-xl border border-parchment-2 overflow-hidden mb-4"><button onClick={()=>setO(!o)} className="w-full flex items-center justify-between px-5 py-4 bg-parchment hover:bg-parchment-2 transition-colors"><div className="flex items-center gap-3"><span className="font-serif text-xl text-slate-600 font-light">{day}</span><span className="text-sm text-ink font-medium">{title}</span></div><span className="text-muted text-lg">{o?"−":"+"}</span></button>{o&&<div className="p-5"><ul className="space-y-2.5 mb-4">{items.map((item,i)=><li key={i} className="flex items-start gap-2.5 text-sm text-muted font-light leading-relaxed"><span className="text-slate-400 mt-1 flex-shrink-0 text-xs">●</span>{item}</li>)}</ul><div className="pt-3 border-t border-parchment-2"><span className="text-xs text-muted font-light">Est. cost: </span><span className="text-xs font-medium text-slate-600">{cost}</span></div></div>}</div>}

export default function SpitiClient(){
  const[m,setM]=useState(false);
  return<>
    <RP/><TableOfContents items={TOC}/><Navbar onPlanTrip={()=>setM(true)}/>
    <Breadcrumb destination="Spiti Valley" />
    <main className="bg-cream min-h-screen">
      <div className="relative h-[60vh] min-h-[420px] overflow-hidden">
        <SmartImage imageKey="spitiHero" fallback="https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1600&q=85" alt="Spiti Valley Key Monastery Himachal Pradesh" fill className="object-cover" priority sizes="100vw" />
        <div className="absolute inset-0 bg-gradient-to-t from-ink/95 via-ink/50 to-ink/30"/>
        <div className="absolute top-24 left-0 right-0 px-6 md:px-14"><div className="max-w-[860px] mx-auto flex items-center gap-2 text-white/50 text-xs"><Link href="/" className="hover:text-gold transition-colors">Home</Link><span>/</span><Link href="/blog" className="hover:text-gold transition-colors">Blog</Link><span>/</span><span className="text-white/70">Spiti Valley 7 Days</span></div></div>
        <div className="absolute bottom-0 left-0 right-0 px-6 md:px-14 pb-10"><div className="max-w-[860px] mx-auto">
          <div className="flex items-center gap-3 mb-4 flex-wrap"><span className="bg-slate-700 text-white text-[0.62rem] tracking-[0.12em] uppercase font-medium px-3 py-1.5 rounded-full">The Middle Land</span><span className="text-white/60 text-xs">March 2026</span><span className="text-white/30">·</span><span className="text-white/60 text-xs">14 min read</span></div>
          <h1 className="font-serif text-[clamp(1.9rem,4.5vw,3.2rem)] font-light text-white leading-[1.08] mb-4">Spiti Valley in 7 Days:<em className="italic text-slate-300"> The Complete Road Trip Guide</em></h1>
          <p className="text-white/65 text-sm font-light max-w-[560px] leading-relaxed">Key Monastery at 4,166m, Chandratal Lake, the world&apos;s oldest mummy at Gue, Pin Valley and a landscape that looks more like Mars than India. Harder than Ladakh. More extraordinary than anything.</p>
        </div></div>
      </div>

      <div className="max-w-[860px] mx-auto px-6 md:px-8 pt-10 pb-20">
        <div className="flex items-center gap-4 text-xs text-muted mb-10 pb-8 border-b border-parchment-2"><span>🏔️ Himachal Pradesh</span><span>·</span><span>🗓 7 Days</span><span>·</span><span>💰 From ₹18,000</span></div>

        <section id="honest" className="mb-14">
          <h2 className="font-serif text-[1.9rem] font-light text-ink mb-4">⚡ What Spiti Actually Is</h2>
          <blockquote className="border-l-4 border-slate-400 pl-6 mb-6 bg-slate-50 rounded-r-xl py-4 pr-4"><p className="font-serif text-[1.05rem] italic text-ink-mid leading-relaxed">Spiti means &quot;the middle land&quot; — between India and Tibet. It sits at 3,800–4,500m in a high-altitude cold desert that receives less than 170mm of rain per year. The air is thin, the roads are rough, the landscape is lunar, and the 1,000-year-old Buddhist monasteries clinging to cliffs above the Spiti River are the most atmospheric places in India.</p></blockquote>
          <p className="text-sm text-muted font-light leading-relaxed mb-4">Spiti is harder than Ladakh in every way — the roads are rougher, the altitude is higher in places, medical facilities are almost non-existent, and mobile network works only in Kaza (BSNL only). But the people who do it say it&apos;s more extraordinary than Ladakh precisely because so few people make the effort.</p>
          <p className="text-sm text-muted font-light leading-relaxed mb-6">The standard circuit: Manali → Rohtang → Kunzum Pass → Kaza → Pin Valley → back via Shimla (or reverse). This is a one-way road trip — you can&apos;t do the same road twice easily. 7 days minimum, 10 days is better.</p>
          <div className="bg-red-50 border border-red-200 rounded-xl p-4 mb-6"><p className="text-sm text-red-800 font-light"><strong className="font-medium">⚠️ Serious preparation required:</strong> Spiti is at 3,500–4,500m. Medical facilities are extremely limited — the nearest decent hospital is Manali (6+ hours). Carry altitude medication (Diamox), a comprehensive first aid kit, and offline maps. This is not a casual trip.</p></div>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3">{[{icon:"🏔️",val:"3,800m",label:"Kaza altitude"},{icon:"🌡️",val:"Jun–Sep",label:"Only window"},{icon:"📵",val:"BSNL only",label:"Network"},{icon:"💰",val:"₹18,000+",label:"Budget from"}].map(s=><div key={s.label} className="bg-white rounded-xl border border-parchment-2 p-4 text-center"><div className="text-2xl mb-1">{s.icon}</div><p className="font-serif text-lg font-light text-ink">{s.val}</p><p className="text-[0.65rem] text-muted uppercase tracking-wide mt-0.5">{s.label}</p></div>)}</div>
        </section>

        <section id="season" className="mb-14">
          <h2 className="font-serif text-[1.9rem] font-light text-ink mb-6">🌡️ When to Go — June to September Only</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
            {[{s:"Jun–Jul",i:"❄️",t:"Early Season — Snow & Wildflowers",d:"Kunzum Pass opens late May–June. Snow still on passes and high fields. Wildflowers carpet the valley June–July. Roads are rough post-winter. Fewer tourists.",b:"Early birds",c:"bg-blue-50 border-blue-200"},{s:"Aug–Sep",i:"☀️",t:"Peak Season — Best Roads",d:"Roads fully cleared and repaired. Warmer days (20–25°C in Kaza). Chandratal is accessible. Most guesthouses open. Peak crowds (still very few vs Ladakh).",b:"Recommended",c:"bg-green-50 border-green-200"},{s:"Oct",i:"🍁",t:"Late Season — Closing Time",d:"Roads start closing from mid-October. Kunzum Pass closes first. Last window before the 6-month winter. Possible but risky — roads can close any day.",b:"Check daily",c:"bg-amber-50 border-amber-200"},{s:"Nov–May",i:"⛄",t:"Completely Closed",d:"Both access routes (Manali side via Kunzum and Shimla side via Kinnaur) close with snow. Spiti is completely cut off. Locals leave or rely on helicopter drops.",b:"Impossible",c:"bg-red-50 border-red-200"}].map(s=><div key={s.s} className={`rounded-xl p-4 border ${s.c}`}><div className="flex items-center gap-2 mb-2"><span className="text-xl">{s.i}</span><div><p className="font-medium text-sm text-ink">{s.s} — {s.t}</p><p className="text-[0.65rem] font-medium text-teal">{s.b}</p></div></div><p className="text-xs text-muted font-light leading-relaxed">{s.d}</p></div>)}
          </div>
        </section>

        <section id="howtoreach" className="mb-14">
          <h2 className="font-serif text-[1.9rem] font-light text-ink mb-6">🚗 The Two Routes Into Spiti</h2>
          <div className="space-y-3">
            {[{i:"🚗",t:"Route 1: Manali → Rohtang → Kunzum → Kaza (harder, more dramatic)",d:"Manali → Rohtang Pass → Gramphoo → Losar → Kunzum Pass (4,551m) → Kaza. 200km, 8–10hrs. Opens June. The road via Kunzum is rough — requires a 4WD or robust SUV. The most dramatic approach — you descend from Rohtang into the moonscape of Spiti.",b:"Most dramatic",c:"bg-slate-50 border-slate-200"},{i:"🚗",t:"Route 2: Shimla → Kinnaur → Recong Peo → Kaza (longer, better road)",d:"Shimla → Rampur → Recong Peo → Nako → Sumdo → Kaza. 350km, 10–12hrs. Open May–November. Better road surface but longer. The Kinnaur Valley along the Sutlej is extraordinary. Best for early/late season.",b:"More reliable",c:"bg-green-50 border-green-200"},{i:"🔄",t:"Recommended circuit: enter one, exit the other",d:"Most people enter via Manali (Jun–Aug) and exit via Shimla–Kinnaur (Aug–Sep). This gives you different scenery both ways and avoids driving the same rough road twice. Total circuit: 600km, 7–10 days.",b:"Best circuit",c:"bg-amber-50 border-amber-200"}].map(t=><div key={t.t} className={`rounded-xl p-4 border ${t.c}`}><div className="flex items-start gap-3"><span className="text-2xl flex-shrink-0">{t.i}</span><div className="flex-1"><div className="flex items-center gap-2 mb-1 flex-wrap"><p className="font-semibold text-sm text-ink">{t.t}</p><span className="text-[0.62rem] bg-white/70 text-muted px-2.5 py-1 rounded-full border border-white/50">{t.b}</span></div><p className="text-xs text-muted font-light leading-relaxed">{t.d}</p></div></div></div>)}
          </div>
        </section>

        <section id="itinerary" className="mb-14">
          <h2 className="font-serif text-[1.9rem] font-light text-ink mb-6">📅 7-Day Itinerary (Manali Entry, Shimla Exit)</h2>
          <D day="Day 1" title="Manali → Kaza via Kunzum Pass" cost="₹2,000–₹4,000" items={["Leave Manali early (5am). Rohtang Permit required (rohtangpermit.com, Rs.550). Cross Rohtang Pass and descend to Gramphoo — the landscape changes instantly from green to lunar brown.", "Losar village (3,960m) — last petrol station before Kaza. Fill up completely. Also stock up on food — very limited options on this road.", "Kunzum Pass (4,551m) — circumambulate the Kunzum Mata temple (tradition before entering Spiti). Extraordinary 360° views. Spend 15 minutes max.", "Arrive Kaza (3,800m) by evening. Check in and REST. Don't go anywhere. Drink 4L water. Mild headache is normal — severe headache or vomiting means descend.", "Kaza has ATMs but they often run out — carry cash from Manali."]}/>
          <D day="Day 2" title="Kaza — Acclimatise + Key Monastery" cost="₹500–₹1,000" items={["Morning: gentle walk around Kaza town. Visit the monastery in Kaza itself (free). Eat light. Drink water constantly.", "Key Monastery (14km from Kaza, 4,166m) — the largest monastery in Spiti, founded in the 11th century. Perched on a pyramidal hill with extraordinary valley views. Monks welcome visitors — morning prayers at 6am are open. Rs.50 entry.", "Don't push altitude on Day 2 — Key Monastery is at 4,166m. Go, see it, return to Kaza. Don't trek above the monastery.", "Evening: Kaza market for Spiti specialties — local honey, dry apricots, frozen yak cheese."]}/>
          <D day="Day 3" title="Hikkim + Komic + Langza + Pin Valley" cost="₹800–₹1,500" items={["Hikkim Post Office — world's highest post office at 4,400m. Send a postcard home (Rs.25). The postmark is unique proof you were here.", "Komic village (4,587m) — one of the world's highest inhabited villages. The 600-year Tangyud Monastery is extraordinary. Very few tourists.", "Langza village — Spiti's fossil village. The hills around Langza are full of marine fossils (this was an ocean floor 50 million years ago). The giant Buddha statue overlooking the valley is iconic.", "Pin Valley National Park (45km from Kaza) — snow leopard habitat. The valley is extremely remote. Mud village at the end of the paved road. Simple homestay available."]}/>
          <D day="Day 4" title="Chandratal Lake" cost="₹1,000–₹2,000" items={["Chandratal Lake — the most extraordinary sight in Spiti. A crescent-shaped lake at 4,300m whose colour shifts between deep blue, turquoise and silver. The drive from Kaza (65km, 3hrs) is as extraordinary as the lake itself.", "Hire a 4WD from Kaza (Rs.3,000–Rs.4,500 for the day) — the last 8km to the lake requires serious off-road capability.", "Camp at Chandratal (several basic camps, Rs.1,500–Rs.3,000/night including meals) for sunrise on the lake — the most otherworldly moment in Himachal.", "No vehicle can drive to the lake edge — 1km walk from the parking. Carry warm clothes even in August — temperature drops below 0°C at night."]}/>
          <D day="Day 5" title="Dhankar + Tabo" cost="₹600–₹1,200" items={["Dhankar Monastery — perched on a crumbling cliff at 3,890m above the confluence of the Spiti and Pin rivers. The old monastery (10th century) is literally falling apart — it&apos;s on the UNESCO emergency list. Visit before it&apos;s gone. The view from the top is one of Spiti&apos;s best.", "Dhankar Lake — 1km trek above the monastery. A small lake completely surrounded by jagged cliffs. Often visible snow leopard tracks in early season.", "Tabo Monastery — founded in 996 CE, the oldest continuously functioning monastery in India. The cave temples carved into the hillside have the most extraordinary murals in the Himalayan world. Rs.100 entry. Photography not allowed inside.", "Stay overnight in Tabo (Rs.500–Rs.1,500)."]}/>
          <D day="Day 6" title="Nako → Recong Peo → Kinnaur Valley" cost="₹1,000–₹2,000" items={["Nako village and lake — a turquoise lake at 3,662m in an extraordinarily remote village. Ancient 1,000-year-old monastery.",  "Begin the Kinnaur descent — the road along the Sutlej River through Kinnaur is one of the most dramatic in India. Sheer cliffs, river far below, road barely wide enough for one vehicle.", "Recong Peo (2,670m) — the first real town since Kaza. ATM, phone network, medical centre. Stock up.", "Sangla Valley side trip (optional) — 15km off the main road, extraordinary apple and apricot orchards in a wide green valley. Very different from Spiti&apos;s lunar landscape."]}/>
          <D day="Day 7" title="Shimla → Delhi" cost="₹1,500–₹3,000" items={["Recong Peo → Shimla: 250km, 6–7hrs. The Kinnaur route follows the Sutlej — extraordinary views of Himalayan foothills.", "Shimla if you want a night: The Mall Road, Christ Church, the toy train views. Or drive straight to Delhi (6hrs more).", "Delhi by evening or next morning depending on Shimla stop."]}/>
        </section>

        <section id="monasteries" className="mb-14">
          <h2 className="font-serif text-[1.9rem] font-light text-ink mb-6">🕌 Monastery Guide</h2>
          <div className="space-y-3">
            {[{n:"Key Monastery",e:"Rs.50",alt:"4,166m",d:"Largest in Spiti — 11th century. 300 monks. Morning prayers 6am open to visitors. The most impressive monastery in terms of scale. The valley view from the gompa is extraordinary.",t:"14km from Kaza"},{n:"Tabo Monastery",e:"Rs.100",alt:"3,360m",d:"Founded 996 CE — oldest continuously functioning monastery in the Himalayas. The cave temples have 1,000-year-old murals of extraordinary quality. Photography not allowed inside — which forces you to really look.",t:"47km from Kaza"},{n:"Dhankar Monastery",e:"Free",alt:"3,890m",d:"10th century monastery literally crumbling off a cliff — on UNESCO emergency list. The old gompa feels genuinely ancient. The new monastery is well maintained. The view over the Spiti–Pin confluence is the best in the valley.",t:"32km from Kaza"},{n:"Komic Monastery",e:"Free",alt:"4,587m",d:"One of the world's highest gompas — 600 years old, perched in one of the world's highest villages. Very few tourists even in peak season. The monks here are almost always happy to talk.",t:"27km from Kaza"},{n:"Gue Mummy",e:"Free",alt:"3,600m",d:"A 500-year-old Buddhist monk mummy naturally preserved by the cold and altitude — the only exposed mummy in India. In a small temple near Gue village. Extraordinarily surreal.",t:"54km from Kaza on Shimla route"}].map(place=><div key={place.n} className="bg-white rounded-xl border border-parchment-2 p-4"><div className="flex items-center justify-between mb-2 flex-wrap gap-2"><p className="font-medium text-sm text-ink">{place.n}</p><div className="flex gap-2"><span className="text-[0.62rem] text-teal font-medium bg-teal/10 px-2 py-0.5 rounded-full">{place.e}</span><span className="text-[0.62rem] bg-slate-50 text-slate-600 px-2 py-0.5 rounded-full border border-slate-200">{place.alt}</span></div></div><p className="text-[0.62rem] text-muted font-light mb-1.5">{place.t}</p><p className="text-xs text-muted font-light leading-relaxed">{place.d}</p></div>)}
          </div>
        </section>

        <section id="budget" className="mb-14">
          <h2 className="font-serif text-[1.9rem] font-light text-ink mb-6">💰 Budget Breakdown</h2>
          <div className="overflow-x-auto rounded-xl border border-parchment-2 shadow-sm">
            <table className="w-full text-sm"><thead><tr className="bg-parchment"><th className="text-left p-3.5 text-xs font-medium text-muted">Category</th><th className="p-3.5 text-xs font-medium text-amber-700 text-center">Budget</th><th className="p-3.5 text-xs font-medium text-slate-700 text-center">Comfortable</th></tr></thead>
            <tbody className="divide-y divide-parchment-2">{[["🚗 Transport (own/hired car 7 days)","₹8,000–₹12,000","₹15,000–₹25,000"],["🏨 Accommodation (6N)","₹3,000–₹6,000","₹6,000–₹15,000"],["🍽 Food (7 days)","₹2,500–₹4,000","₹4,000–₹7,000"],["⛺ Chandratal camping","₹1,500–₹2,000","₹2,500–₹4,000"],["🎯 Entry + Activities","₹800–₹1,200","₹1,500–₹2,500"],["TOTAL per person","₹18,000–₹28,000","₹28,000–₹50,000"]].map(([cat,...vals])=><tr key={cat} className="bg-white hover:bg-parchment/40 transition-colors"><td className="p-3.5 text-xs text-ink font-medium">{cat}</td>{vals.map((v,i)=><td key={i} className="p-3.5 text-xs text-muted font-light text-center">{v}</td>)}</tr>)}</tbody></table>
          </div>
        </section>

        <AffiliateBlock destination="Spiti Valley Himachal Pradesh" hotels={[{name:"Spiti Holiday Camp",type:"Camp · Kaza",price:"From ₹2,500/night",rating:"4",badge:"Best Kaza",url:"https://www.booking.com/hotel/in/spiti-holiday-camp.html?aid=YOUR_AFFILIATE_ID"},{name:"Chandratal Lake Camp",type:"Luxury camp · Chandratal",price:"From ₹4,000/night",rating:"4",badge:"Lakeside",url:"https://www.booking.com/hotel/in/chandratal-camp.html?aid=YOUR_AFFILIATE_ID"},{name:"Homestay Tabo",type:"Homestay · Tabo village",price:"From ₹800/night",rating:"3",badge:"Oldest village",url:"https://www.booking.com/hotel/in/homestay-tabo.html?aid=YOUR_AFFILIATE_ID"},{name:"Norling Guest House Kaza",type:"Guesthouse · Kaza town",price:"From ₹1,200/night",rating:"3",badge:"Best budget",url:"https://www.booking.com/hotel/in/norling-kaza.html?aid=YOUR_AFFILIATE_ID"}]} activities={[{name:"Spiti Valley 7-Day Guided Tour",duration:"7 Days",price:"From ₹18,000/person",badge:"Fully guided",url:"https://www.getyourguide.com/manali-l3008/?partner_id=PSZA5UI"},{name:"Chandratal Lake Camping + Trek",duration:"2 Days",price:"From ₹3,500/person",badge:"Must do",url:"https://www.getyourguide.com/manali-l3008/?partner_id=PSZA5UI"},{name:"Key Monastery + Villages Day Tour",duration:"Full day",price:"From ₹1,500/person",url:"https://www.getyourguide.com/manali-l3008/?partner_id=PSZA5UI"},{name:"Snow Leopard Safari Pin Valley",duration:"2 Days",price:"From ₹5,000/person",url:"https://www.getyourguide.com/manali-l3008/?partner_id=PSZA5UI"}]}/>

        <DestinationGallery title="Spiti Valley" subtitle="The Middle Land — between India and Tibet." spots={[{name:"Key Monastery",query:"key monastery spiti valley cliff himachal pradesh buddhist",desc:"11th-century monastery perched on a cliff at 4,166m — the largest in Spiti."},{name:"Chandratal Lake",query:"chandratal lake spiti valley blue mountain reflection",desc:"Crescent-shaped lake at 4,300m — colour shifts between blue, turquoise and silver."},{name:"Spiti River Valley",query:"spiti valley river lunar landscape himachal pradesh mountains",desc:"The Spiti River through the high-altitude cold desert — a lunar landscape unlike anything in India."},{name:"Langza Buddha",query:"langza village spiti valley buddha statue mountains fossil",desc:"The giant Buddha statue in Langza — a village famous for marine fossils from when this was ocean floor."},{name:"Dhankar Monastery",query:"dhankar monastery cliff spiti valley confluence",desc:"10th-century monastery crumbling off a cliff above the Spiti–Pin river confluence."}]}/>

        <section id="tips" className="mb-14">
          <h2 className="font-serif text-[1.9rem] font-light text-ink mb-6">💡 Pro Tips</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
            {[{i:"📵",t:"BSNL SIM is mandatory",d:"Airtel and Jio have zero signal in Spiti. Buy a BSNL SIM in Manali or Shimla. Even BSNL is patchy in remote areas. Download offline maps for all of Himachal Pradesh before entering.",c:"bg-amber-50 border-amber-200"},{i:"💰",t:"Carry 3–4 days of cash minimum",d:"ATMs in Kaza are unreliable — often empty or broken. The nearest working ATM backup is Recong Peo (Kinnaur side) or Manali. Carry Rs.8,000–Rs.12,000 cash per person minimum.",c:"bg-green-50 border-green-200"},{i:"⛽",t:"Petrol: fill at every opportunity",d:"Losar (before Kunzum) is the last petrol before Kaza from Manali side. Kaza has petrol. Then nothing reliable until Recong Peo. Never enter Spiti with less than a full tank.",c:"bg-blue-50 border-blue-200"},{i:"🏥",t:"First aid + Diamox are not optional",d:"The nearest hospital is Manali (6+ hours). Carry: Diamox (acetazolamide), Diamox prophylaxis, basic wound kit, pain relief, rehydration salts. Consult a doctor before departure.",c:"bg-red-50 border-red-200"},{i:"🚗",t:"4WD strongly recommended",d:"The Kunzum Pass approach and many village roads require real ground clearance. A Bolero, Scorpio, Fortuner or Thar handles Spiti roads. A Sedan or basic hatchback is a bad idea.",c:"bg-slate-50 border-slate-200"},{i:"🌌",t:"The Milky Way from Chandratal",d:"At 4,300m with zero light pollution, the Milky Way is so bright at Chandratal that you can read by it. Stay overnight at the lake. Bring a sleeping bag rated to -10°C.",c:"bg-purple-50 border-purple-200"}].map(t=><div key={t.t} className={`rounded-xl p-4 border ${t.c}`}><div className="flex items-start gap-3"><span className="text-xl flex-shrink-0">{t.i}</span><div><p className="font-medium text-sm text-ink mb-1">{t.t}</p><p className="text-xs text-muted font-light leading-relaxed">{t.d}</p></div></div></div>)}
          </div>
        </section>

        <div className="mb-14 bg-ink rounded-2xl p-8 text-center">
          <span className="text-[0.65rem] tracking-[0.2em] uppercase text-gold block mb-3">Free Service</span>
          <h2 className="font-serif text-[1.9rem] font-light text-white mb-3">Want Your Spiti Trip Planned?</h2>
          <p className="text-sm text-white/55 font-light mb-7 max-w-[380px] mx-auto leading-relaxed">Spiti logistics are complex. Tell us your dates and we&apos;ll build a complete circuit plan in 24 hours. Free.</p>
          <button onClick={()=>setM(true)} className="btn-gold">Plan My Spiti Trip →</button>
        </div>

        <section id="faq" className="mb-14">
          <h2 className="font-serif text-[1.9rem] font-light text-ink mb-6">❓ FAQ</h2>
          <div className="space-y-3">
            {[{q:"When is Spiti Valley open?",a:"June to October only. Manali–Spiti via Kunzum opens late May–June. Shimla–Kinnaur route opens slightly earlier (May) and later (November). Completely snow-locked November–May."},{q:"Is Spiti harder than Ladakh?",a:"Yes — roads are rougher, altitude is higher in places (Chandratal 4,300m, Komic 4,587m), medical facilities almost non-existent, mobile network almost absent. More remote and more rewarding."},{q:"Do I need a permit for Spiti?",a:"Indian nationals need no permit for Spiti. Foreigners need an Inner Line Permit for Pin Valley and areas near the Tibet border — available at the DC office in Recong Peo."},{q:"Is Spiti suitable for solo travel?",a:"Yes but with preparation: carry a comprehensive first aid kit, BSNL SIM, offline maps, altitude medication, and enough cash. Tell someone your itinerary. Don't attempt remote areas alone."},{q:"Can I do Spiti without a 4WD?",a:"Technically possible in summer (Aug) on the Shimla–Kinnaur route in a regular car. But the Manali–Kunzum–Kaza route requires good ground clearance. For Chandratal and village roads, 4WD is strongly recommended."}].map((item,i)=><FAQ key={i} {...item}/>)}
          </div>
        </section>
        <Comments/>
        <section className="mt-14"><h3 className="font-serif text-lg font-light text-ink mb-4">More Mountain Guides</h3>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">{[{label:"Manali 5 Days — Gateway to Spiti",href:"/blog/manali-5-days"},{label:"Leh Ladakh 7 Days — Bucket List",href:"/blog/leh-ladakh-7-days"},{label:"Jibhi & Tirthan Valley 3 Days",href:"/blog/jibhi-tirthan-valley-3-days"},{label:"Kashmir 6 Days — Heaven on Earth",href:"/blog/kashmir-6-days"}].map(link=><Link key={link.label} href={link.href} className="flex items-center justify-between p-4 bg-white rounded-lg border border-parchment-2 hover:border-gold hover:shadow-sm transition-all duration-200 group"><span className="text-sm text-ink font-light group-hover:text-teal transition-colors">{link.label}</span><span className="text-xs text-muted">Read →</span></Link>)}</div>
        </section>
        <RelatedGuides currentSlug="spiti-valley-7-days" />
      </div>
    </main>
    <Footer/><InquiryModal isOpen={m} onClose={()=>setM(false)}/>
  </>;
}
