import { MetadataRoute } from "next";

export default function sitemap(): MetadataRoute.Sitemap {
  const base = "https://www.incredibleitinerary.com";
  const now = new Date();

  return [
    { url: base,                                      lastModified: now, changeFrequency: "weekly",  priority: 1.0 },
    { url: `${base}/blog`,                            lastModified: now, changeFrequency: "weekly",  priority: 0.9 },
    { url: `${base}/quiz`,                            lastModified: now, changeFrequency: "monthly", priority: 0.9 },
    { url: `${base}/shop`,                            lastModified: now, changeFrequency: "weekly",  priority: 0.85 },
    { url: `${base}/about`,                           lastModified: now, changeFrequency: "monthly", priority: 0.6 },
    { url: `${base}/contact`,                         lastModified: now, changeFrequency: "monthly", priority: 0.6 },
    { url: `${base}/privacy`,                         lastModified: now, changeFrequency: "yearly",  priority: 0.3 },
    { url: `${base}/terms`,                           lastModified: now, changeFrequency: "yearly",  priority: 0.3 },
    { url: `${base}/cookies`,                         lastModified: now, changeFrequency: "yearly",  priority: 0.3 },
    { url: `${base}/blog/kashmir-6-days`,             lastModified: now, changeFrequency: "monthly", priority: 0.9 },
    { url: `${base}/blog/leh-ladakh-7-days`,          lastModified: now, changeFrequency: "monthly", priority: 0.9 },
    { url: `${base}/blog/manali-5-days`,              lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/golden-triangle-7-days`,     lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/rajasthan-7-days`,           lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/andaman-5-days`,             lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/kerala-5-days`,              lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/goa-3-days`,                 lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/varanasi-3-days`,            lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/coorg-3-days`, lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${base}/blog/rishikesh-haridwar-3-days`, lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/jibhi-tirthan-valley-3-days`, lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${base}/blog/hampi-3-days`, lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${base}/blog/spiti-valley-7-days`, lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/meghalaya-5-days`, lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/sikkim-6-days`, lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/pondicherry-3-days`, lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${base}/blog/gujarat-7-days`, lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/amritsar-2-days`, lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${base}/blog/dharamshala-3-days`, lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${base}/blog/udaipur-3-days`, lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/jaipur-3-days`, lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/ooty-3-days`, lastModified: now, changeFrequency: "monthly", priority: 0.86 },
    { url: `${base}/blog/darjeeling-4-days`, lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${base}/blog/mysore-3-days`, lastModified: now, changeFrequency: "monthly", priority: 0.86 },
    { url: `${base}/blog/gokarna-3-days`, lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/shimla-3-days`, lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${base}/blog/kasol-3-days`, lastModified: now, changeFrequency: "monthly", priority: 0.86 },
    { url: `${base}/blog/nainital-3-days`, lastModified: now, changeFrequency: "monthly", priority: 0.86 },
    { url: `${base}/blog/agra-2-days`, lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/jodhpur-3-days`, lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${base}/blog/jaisalmer-3-days`, lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${base}/blog/khajuraho-2-days`, lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/orchha-2-days`, lastModified: now, changeFrequency: "monthly", priority: 0.84 },
    { url: `${base}/blog/mussoorie-3-days`, lastModified: now, changeFrequency: "monthly", priority: 0.86 },
    { url: `${base}/blog/auli-3-days`, lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/kodaikanal-3-days`, lastModified: now, changeFrequency: "monthly", priority: 0.86 },
    { url: `${base}/blog/jim-corbett-3-days`, lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${base}/blog/ranthambore-3-days`, lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${base}/blog/alleppey-3-days`, lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${base}/blog/munnar-3-days`, lastModified: now, changeFrequency: "monthly", priority: 0.86 },
    { url: `${base}/blog/wayanad-3-days`, lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/pushkar-2-days`, lastModified: now, changeFrequency: "monthly", priority: 0.84 },
    { url: `${base}/blog/madurai-2-days`, lastModified: now, changeFrequency: "monthly", priority: 0.86 },
    { url: `${base}/blog/hyderabad-3-days`, lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${base}/blog/vizag-3-days`, lastModified: now, changeFrequency: "monthly", priority: 0.84 },
    { url: `${base}/blog/kanyakumari-2-days`, lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/rameswaram-2-days`, lastModified: now, changeFrequency: "monthly", priority: 0.84 },
    { url: `${base}/blog/mount-abu-2-days`, lastModified: now, changeFrequency: "monthly", priority: 0.84 },
    { url: `${base}/blog/diu-2-days`, lastModified: now, changeFrequency: "monthly", priority: 0.83 },
    { url: `${base}/blog/dwarka-2-days`, lastModified: now, changeFrequency: "monthly", priority: 0.83 },
    { url: `${base}/blog/lonavala-2-days`, lastModified: now, changeFrequency: "monthly", priority: 0.84 },
    { url: `${base}/blog/kaziranga-3-days`, lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${base}/blog/shillong-3-days`, lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/mahabaleshwar-2-days`, lastModified: now, changeFrequency: "monthly", priority: 0.83 },
    { url: `${base}/blog/tawang-4-days`, lastModified: now, changeFrequency: "monthly", priority: 0.86 },
    { url: `${base}/blog/sundarbans-3-days`, lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/valley-of-flowers-4-days`, lastModified: now, changeFrequency: "monthly", priority: 0.86 },
    { url: `${base}/blog/majuli-3-days`, lastModified: now, changeFrequency: "monthly", priority: 0.84 },
    { url: `${base}/compare/goa-vs-pondicherry`, lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/compare/shimla-vs-manali`, lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/compare/kashmir-vs-ladakh`, lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/compare/jaipur-vs-udaipur`, lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/compare/ooty-vs-kodaikanal`, lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/compare/thailand-vs-bali`, lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/compare/goa-vs-phuket`, lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/compare/tokyo-vs-kyoto`, lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/compare/dubai-vs-singapore`, lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/compare/barcelona-vs-rome`, lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    // International
    { url: `${base}/blog/bangkok-4-days`, lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/phuket-5-days`, lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/chiang-mai-4-days`, lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/tokyo-5-days`, lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/kyoto-4-days`, lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/osaka-3-days`, lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/rome-4-days`, lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/florence-3-days`, lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/amalfi-coast-4-days`, lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    // Tools
    { url: `${base}/tools/trip-calculator`, lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/tools/visa-checker`, lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    // Indonesia
    { url: `${base}/blog/bali-5-days`, lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/ubud-3-days`, lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${base}/blog/lombok-4-days`, lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    // UAE & Oman
    { url: `${base}/blog/dubai-4-days`, lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/abu-dhabi-3-days`, lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${base}/blog/muscat-3-days`, lastModified: now, changeFrequency: "monthly", priority: 0.86 },
    // Spain
    { url: `${base}/blog/barcelona-4-days`, lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/madrid-3-days`, lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/seville-3-days`, lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    // Vietnam
    { url: `${base}/blog/hanoi-3-days`, lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/ho-chi-minh-city-3-days`, lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/ha-long-bay-3-days`, lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    // Greece
    { url: `${base}/blog/athens-3-days`, lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/santorini-4-days`, lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    { url: `${base}/blog/crete-5-days`, lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    // Turkey
    { url: `${base}/blog/istanbul-5-days`, lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    { url: `${base}/blog/cappadocia-3-days`, lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/antalya-3-days`, lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    // Maldives
    { url: `${base}/blog/maldives-5-days`, lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    // Singapore
    { url: `${base}/blog/singapore-3-days`, lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    // Portugal
    { url: `${base}/blog/lisbon-4-days`, lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/porto-3-days`, lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/algarve-4-days`, lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    // Malaysia
    { url: `${base}/blog/kuala-lumpur-3-days`, lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/langkawi-3-days`, lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${base}/blog/penang-3-days`, lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    // France
    { url: `${base}/blog/paris-5-days`,             lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    { url: `${base}/blog/nice-3-days`,              lastModified: now, changeFrequency: "monthly", priority: 0.89 },
    { url: `${base}/blog/lyon-3-days`,              lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/bordeaux-3-days`,          lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/provence-4-days`,          lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/mont-saint-michel-2-days`, lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${base}/blog/strasbourg-3-days`,        lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${base}/blog/marseille-3-days`,         lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    // USA
    { url: `${base}/blog/new-york-5-days`,     lastModified: now, changeFrequency: "monthly", priority: 0.93 },
    { url: `${base}/blog/los-angeles-5-days`,  lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    { url: `${base}/blog/hawaii-7-days`,       lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    { url: `${base}/blog/las-vegas-4-days`,    lastModified: now, changeFrequency: "monthly", priority: 0.91 },
    { url: `${base}/blog/miami-4-days`,        lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/grand-canyon-3-days`, lastModified: now, changeFrequency: "monthly", priority: 0.91 },
    // UK
    { url: `${base}/blog/london-5-days`,    lastModified: now, changeFrequency: "monthly", priority: 0.93 },
    { url: `${base}/blog/edinburgh-4-days`, lastModified: now, changeFrequency: "monthly", priority: 0.91 },
    { url: `${base}/blog/bath-2-days`,      lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/cotswolds-3-days`, lastModified: now, changeFrequency: "monthly", priority: 0.89 },
    // Tools
    { url: `${base}/tools/packing-list`, lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/tools/currency-converter`, lastModified: now, changeFrequency: "monthly", priority: 0.88 },
  ];
}
