"use client";
import { useState, useEffect } from "react";
import Link from "next/link";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import InquiryModal from "@/components/ui/InquiryModal";
import TableOfContents from "@/components/blog/TableOfContents";
import Comments from "@/components/blog/Comments";
import DestinationGallery from "@/components/blog/DestinationGallery";
import AffiliateBlock from "@/components/blog/AffiliateBlock";
import SmartImage from "@/components/ui/SmartImage";
import RelatedGuides from "@/components/blog/RelatedGuides";
import Breadcrumb from "@/components/blog/Breadcrumb";

const TOC=[{id:"honest",emoji:"⚡",label:"What Hampi Actually Is"},{id:"season",emoji:"🌡️",label:"Best Time"},{id:"howtoreach",emoji:"🚂",label:"Getting There"},{id:"itinerary",emoji:"📅",label:"3-Day Itinerary"},{id:"ruins",emoji:"🏛️",label:"Temple Guide"},{id:"budget",emoji:"💰",label:"Budget"},{id:"tips",emoji:"💡",label:"Pro Tips"},{id:"faq",emoji:"❓",label:"FAQ"}];

function RP(){const[p,setP]=useState(0);useEffect(()=>{const u=()=>{const e=document.documentElement;setP(Math.min(100,(e.scrollTop/(e.scrollHeight-e.clientHeight))*100))};window.addEventListener("scroll",u,{passive:true});return()=>window.removeEventListener("scroll",u)},[]);return<div className="fixed top-0 left-0 right-0 z-[300] h-1 bg-parchment-2"><div className="h-full bg-amber-600 transition-all duration-100" style={{width:`${p}%`}}/></div>}
function FAQ({q,a}:{q:string;a:string}){const[o,setO]=useState(false);return<div className="border border-parchment-2 rounded-xl overflow-hidden bg-white"><button onClick={()=>setO(!o)} className="w-full flex items-center justify-between px-5 py-4 text-left hover:bg-parchment transition-colors"><span className="font-medium text-sm text-ink pr-4">{q}</span><span className={`text-amber-600 text-lg flex-shrink-0 transition-transform duration-200 ${o?"rotate-45":""}`}>+</span></button>{o&&<div className="px-5 pb-5 pt-1 border-t border-parchment-2"><p className="text-sm text-muted font-light leading-relaxed">{a}</p></div>}</div>}
function D({day,title,items,cost}:{day:string;title:string;items:string[];cost:string}){const[o,setO]=useState(true);return<div className="bg-white rounded-xl border border-parchment-2 overflow-hidden mb-4"><button onClick={()=>setO(!o)} className="w-full flex items-center justify-between px-5 py-4 bg-parchment hover:bg-parchment-2 transition-colors"><div className="flex items-center gap-3"><span className="font-serif text-xl text-amber-600 font-light">{day}</span><span className="text-sm text-ink font-medium">{title}</span></div><span className="text-muted text-lg">{o?"−":"+"}</span></button>{o&&<div className="p-5"><ul className="space-y-2.5 mb-4">{items.map((item,i)=><li key={i} className="flex items-start gap-2.5 text-sm text-muted font-light leading-relaxed"><span className="text-amber-500 mt-1 flex-shrink-0 text-xs">●</span>{item}</li>)}</ul><div className="pt-3 border-t border-parchment-2"><span className="text-xs text-muted font-light">Est. cost: </span><span className="text-xs font-medium text-amber-600">{cost}</span></div></div>}</div>}

export default function HampiClient(){
  const[m,setM]=useState(false);
  return<>
    <RP/><TableOfContents items={TOC}/><Navbar onPlanTrip={()=>setM(true)}/>
    <Breadcrumb destination="Hampi" />
    <main className="bg-cream min-h-screen">
      <div className="relative h-[60vh] min-h-[420px] overflow-hidden">
        <SmartImage imageKey="hampiHero" fallback="https://images.unsplash.com/photo-1605640840605-14ac1855827b?w=1600&q=85" alt="Hampi Vijayanagara ruins boulders Karnataka" fill className="object-cover" priority sizes="100vw" />
        <div className="absolute inset-0 bg-gradient-to-t from-ink/95 via-ink/50 to-ink/30"/>
        <div className="absolute top-24 left-0 right-0 px-6 md:px-14"><div className="max-w-[860px] mx-auto flex items-center gap-2 text-white/50 text-xs"><Link href="/" className="hover:text-gold transition-colors">Home</Link><span>/</span><Link href="/blog" className="hover:text-gold transition-colors">Blog</Link><span>/</span><span className="text-white/70">Hampi 3 Days</span></div></div>
        <div className="absolute bottom-0 left-0 right-0 px-6 md:px-14 pb-10"><div className="max-w-[860px] mx-auto">
          <div className="flex items-center gap-3 mb-4 flex-wrap"><span className="bg-amber-700 text-white text-[0.62rem] tracking-[0.12em] uppercase font-medium px-3 py-1.5 rounded-full">UNESCO World Heritage</span><span className="text-white/60 text-xs">March 2026</span><span className="text-white/30">·</span><span className="text-white/60 text-xs">12 min read</span></div>
          <h1 className="font-serif text-[clamp(1.9rem,4.5vw,3.2rem)] font-light text-white leading-[1.08] mb-4">Hampi in 3 Days:<em className="italic text-amber-300"> India&apos;s Most Surreal Landscape</em></h1>
          <p className="text-white/65 text-sm font-light max-w-[560px] leading-relaxed">14th-century Vijayanagara empire ruins scattered among giant boulders, a hippie island, the stone chariot of Vittala Temple, and sunsets that look painted. The complete guide.</p>
        </div></div>
      </div>

      <div className="max-w-[860px] mx-auto px-6 md:px-8 pt-10 pb-20">
        <div className="flex items-center gap-4 text-xs text-muted mb-10 pb-8 border-b border-parchment-2"><span>🏛️ Karnataka</span><span>·</span><span>🗓 3 Days</span><span>·</span><span>💰 From ₹3,500</span></div>

        <section id="honest" className="mb-14">
          <h2 className="font-serif text-[1.9rem] font-light text-ink mb-4">⚡ What Hampi Actually Is</h2>
          <blockquote className="border-l-4 border-amber-500 pl-6 mb-6 bg-amber-50 rounded-r-xl py-4 pr-4"><p className="font-serif text-[1.05rem] italic text-ink-mid leading-relaxed">Hampi is what happens when a 14th-century empire falls apart among the strangest geology on earth. Giant smooth granite boulders the size of houses are stacked in impossible formations across 26 square kilometres. Among them: 1,600 temples, market ruins, an elephant stable, a water tank the size of a stadium, and the Tungabhadra River running cool and quiet through all of it.</p></blockquote>
          <p className="text-sm text-muted font-light leading-relaxed mb-4">The Vijayanagara Empire was at its peak the wealthiest city in the world outside Beijing. At its height Hampi had 500,000 residents. The Portuguese traveller Domingo Paes described it as &quot;the best-provided city in the world.&quot; It was sacked and destroyed in 1565 CE by the Deccan Sultanates — abandoned overnight and never rebuilt.</p>
          <p className="text-sm text-muted font-light leading-relaxed mb-6">What remains is a UNESCO World Heritage Site of staggering scale — honestly, nothing in India prepares you for how vast it is. You can spend three days here and still not see everything. Rent a bicycle — the ruins are spread over too large an area to walk and too small for a car.</p>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3">{[{icon:"🚂",val:"7–8hrs",label:"From Bangalore"},{icon:"🌡️",val:"Oct–Feb",label:"Best season"},{icon:"🏛️",val:"1,600+",label:"Monuments"},{icon:"💰",val:"₹3,500+",label:"Budget from"}].map(s=><div key={s.label} className="bg-white rounded-xl border border-parchment-2 p-4 text-center"><div className="text-2xl mb-1">{s.icon}</div><p className="font-serif text-lg font-light text-ink">{s.val}</p><p className="text-[0.65rem] text-muted uppercase tracking-wide mt-0.5">{s.label}</p></div>)}</div>
        </section>

        <section id="season" className="mb-14">
          <h2 className="font-serif text-[1.9rem] font-light text-ink mb-6">🌡️ Best Time to Visit</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
            {[{s:"Oct–Feb",i:"☀️",t:"Winter — Best Season",d:"20–28°C, comfortable for exploring ruins all day. October and November have post-monsoon greenery — boulders with grass. December–February is peak season and busy. Best overall.",b:"Recommended",c:"bg-green-50 border-green-200"},{s:"Mar–Apr",i:"🌅",t:"Spring — Before the Heat",d:"Still manageable 25–33°C. Dawn visits are comfortable. Afternoons get hot. Fewer crowds than December–January. Viable with early morning starts.",b:"Morning only",c:"bg-amber-50 border-amber-200"},{s:"May–Jun",i:"🔥",t:"Summer — Very Hot",d:"38–42°C. Dangerously hot for walking ruins in the afternoon. Early morning only. Not recommended unless you must travel in summer.",b:"Avoid afternoons",c:"bg-orange-50 border-orange-200"},{s:"Jul–Sep",i:"🌧️",t:"Monsoon — Green & Empty",d:"Lush green boulders and ruins in the rain — beautiful. But many roads flood and river crossing to hippie island may close. Very few tourists.",b:"For rain lovers",c:"bg-blue-50 border-blue-200"}].map(s=><div key={s.s} className={`rounded-xl p-4 border ${s.c}`}><div className="flex items-center gap-2 mb-2"><span className="text-xl">{s.i}</span><div><p className="font-medium text-sm text-ink">{s.s} — {s.t}</p><p className="text-[0.65rem] font-medium text-teal">{s.b}</p></div></div><p className="text-xs text-muted font-light leading-relaxed">{s.d}</p></div>)}
          </div>
        </section>

        <section id="howtoreach" className="mb-14">
          <h2 className="font-serif text-[1.9rem] font-light text-ink mb-6">🚂 Getting to Hampi</h2>
          <div className="bg-amber-50 border border-amber-200 rounded-xl p-4 mb-4"><p className="text-sm text-amber-800 font-light"><strong className="font-medium">Note:</strong> The nearest railway station is Hosapete Junction (13km from Hampi). Most people take a train or overnight bus from Bangalore to Hosapete, then auto/taxi to Hampi.</p></div>
          <div className="space-y-3">
            {[{i:"🚂",t:"Train from Bangalore (recommended)",d:"Bangalore → Hosapete: 7–8hrs, Rs.200–Rs.600. Multiple trains daily including overnight options. Then auto to Hampi: Rs.200–Rs.300, 20 mins.",b:"Best option",c:"bg-green-50 border-green-200"},{i:"🚌",t:"Overnight bus from Bangalore",d:"Direct buses from Majestic to Hosapete (8hrs, Rs.400–Rs.900). Some services go to Hampi directly. Book on redbus.in.",b:"Budget option",c:"bg-amber-50 border-amber-200"},{i:"🚗",t:"Drive from Bangalore",d:"350km via NH150C, 6–7hrs. Straight highway most of the way. Scenic last 50km through Deccan plateau.",b:"Flexible",c:"bg-parchment border-parchment-2"}].map(t=><div key={t.t} className={`rounded-xl p-4 border ${t.c}`}><div className="flex items-start gap-3"><span className="text-2xl flex-shrink-0">{t.i}</span><div className="flex-1"><div className="flex items-center gap-2 mb-1 flex-wrap"><p className="font-semibold text-sm text-ink">{t.t}</p><span className="text-[0.62rem] bg-white/70 text-muted px-2.5 py-1 rounded-full border border-white/50">{t.b}</span></div><p className="text-xs text-muted font-light leading-relaxed">{t.d}</p></div></div></div>)}
          </div>
        </section>

        <section id="itinerary" className="mb-14">
          <h2 className="font-serif text-[1.9rem] font-light text-ink mb-6">📅 3-Day Itinerary</h2>
          <D day="Day 1" title="Royal Centre + Virupaksha Temple + Sunset" cost="₹600–₹1,200" items={["Arrive Hampi, check in near Virupaksha Temple (Hampi Bazaar side, Rs.400–Rs.1,500/night) or Hippie Island (cross the coracle — Rs.20–Rs.30, more relaxed vibe).", "Rent a bicycle (Rs.100–Rs.150/day) — essential for covering the ruins. Hampi Bazaar to Vittala Temple is 2.5km; impossible on foot in the heat.", "Royal Enclosure — the ruined palace complex of the Vijayanagara kings. Stepped water tanks, elephant stables (the best preserved structure), queen's bath (surprisingly moving — it's just an open-air pool but the scale hits you). Rs.40 entry (as of early 2026).", "Virupaksha Temple (free entry) — this temple never stopped functioning since the 9th century. Morning puja is genuinely hypnotic — incense, bells, and the sound bouncing off 1,200-year-old stone. The view of the ruins from the top of the gopuram is the best overview of Hampi.", "Sunset from Hemakuta Hill — the hill directly behind Hampi Bazaar covered in small temples. Best sunset spot in Hampi. Free. Arrive 30 mins before sunset for a spot on the rocks."]}/>
          <D day="Day 2" title="Vittala Temple + Hippie Island + Bouldering" cost="₹500–₹1,000" items={["6:30am: Vittala Temple (Rs.600 entry as of early 2026, also covers Hampi Bazaar). Go at opening to avoid the crowds that arrive by 10am. The stone chariot in front of the main temple is the icon of Hampi — it was once used as a lighthouse. The musical pillars (56 pillars that produce different notes when tapped) are genuinely mind-blowing — tap one and hear a clear metallic note ring out of solid granite.", "The Vittala Temple complex is 1.5km end to end — the most impressive single site in Hampi. Spend 2–3 hours. Bring water.", "Afternoon: Hippie Island (Virupapur Gadde) — cross the Tungabhadra by coracle (Rs.20–Rs.30). The island has guesthouses, cafes (Laughing Buddha, Mango Tree), and walking trails through banana and papaya farms to quiet river spots.", "Sunset boulder scramble — there are dozens of natural boulder formations you can climb near the island. The view of the Tungabhadra with the ruins in the background at sunset is one of those scenes that doesn't look real. No entry fee. What most blogs won't tell you: the best bouldering spots are on the Hippie Island side, not the temple side.", "Dinner at Mango Tree restaurant on the island — overhanging the river, fairy lights, good food (Rs.150–Rs.350)."]}/>
          <D day="Day 3" title="Sanapur Lake + Anegundi + Depart" cost="₹400–₹800" items={["Sanapur Lake — 3km from the island, a reservoir perfect for swimming (not the Tungabhadra — currents are dangerous). Locals coracle trips on the lake (Rs.100–Rs.150 for 30 mins). Very few tourists.", "Anegundi village — across the river from Hampi, believed to be the monkey kingdom Kishkindha from the Ramayana. Ancient temples, Anjaneya Hill with a Hanuman temple at the top (582 steps, panoramic views of the entire boulder landscape). Free.", "Matanga Hill — the highest point in Hampi. The sunrise from Matanga Hill is worth the 5am alarm — I've done it three times and still get chills. 30-minute climb from Hampi Bazaar. Rs.50 entry.", "Skip the Hampi Bazaar shops unless you want overpriced souvenirs identical to what you'll find everywhere in Karnataka. If you do want something, the stone carvings from the small workshop past the last temple on the bazaar road are the only genuinely local pieces."]}/>
        </section>

        <section id="ruins" className="mb-14">
          <h2 className="font-serif text-[1.9rem] font-light text-ink mb-6">🏛️ Temple & Ruins Guide</h2>
          <div className="space-y-3">
            {[{n:"Vittala Temple",e:"Rs.600",d:"The masterpiece of Vijayanagara architecture. Stone chariot, 56 musical pillars, kalyana mandapa (marriage hall). The most photographed structure in Hampi. Go at 6:30am opening.",t:"Must see · 2–3hrs"},{n:"Virupaksha Temple",e:"Free",d:"The only continuously functioning temple in Hampi since the 9th century — 1,200+ years of uninterrupted worship. The elephant Lakshmi blesses visitors for a small tip. Morning puja at 6am is deeply atmospheric — last time I went, the priest waved us right up to the inner sanctum.",t:"Must see · 1hr"},{n:"Royal Enclosure",e:"Rs.40",d:"The ruined palace, stepped water tanks, elephant stables (remarkably well preserved), underground chamber. The queen's bath (an outdoor swimming pool for royalty) is peculiarly moving.",t:"Must see · 1.5hrs"},{n:"Hemakuta Hill",e:"Free",d:"30+ Jain and Shaivite temples on a rocky hill — some from the pre-Vijayanagara period (9th–14th century). Best place in Hampi for photography and sunset views.",t:"Sunset · 1hr"},{n:"Zanana Enclosure",e:"Rs.40",d:"The Lotus Mahal — the most ornate building in the Royal Quarter. A pavilion that blends Hindu and Islamic architectural styles so seamlessly you can't tell where one ends and the other begins. Underground passages connecting to the rest of the enclosure.",t:"30 mins"}].map(place=><div key={place.n} className="bg-white rounded-xl border border-parchment-2 p-4"><div className="flex items-center justify-between mb-2 flex-wrap gap-2"><p className="font-medium text-sm text-ink">{place.n}</p><div className="flex gap-2"><span className="text-[0.62rem] text-teal font-medium bg-teal/10 px-2 py-0.5 rounded-full">{place.e}</span><span className="text-[0.62rem] bg-amber-50 text-amber-700 px-2 py-0.5 rounded-full border border-amber-200">{place.t}</span></div></div><p className="text-xs text-muted font-light leading-relaxed">{place.d}</p></div>)}
          </div>
        </section>

        <section id="budget" className="mb-14">
          <h2 className="font-serif text-[1.9rem] font-light text-ink mb-6">💰 Budget Breakdown</h2>
          <div className="overflow-x-auto rounded-xl border border-parchment-2 shadow-sm">
            <table className="w-full text-sm"><thead><tr className="bg-parchment"><th className="text-left p-3.5 text-xs font-medium text-muted">Category</th><th className="p-3.5 text-xs font-medium text-amber-700 text-center">Budget</th><th className="p-3.5 text-xs font-medium text-rose-700 text-center">Mid-Range</th></tr></thead>
            <tbody className="divide-y divide-parchment-2">{[["🚂 Transport (Bangalore return)","₹400–₹1,200","₹400–₹1,200"],["🏨 Accommodation (2N)","₹800–₹2,000","₹2,500–₹5,000"],["🚲 Bicycle rental (2 days)","₹200–₹300","₹200–₹300"],["🏛️ Entry fees","₹700–₹1,000","₹700–₹1,000"],["🍽 Food (3 days)","₹600–₹1,000","₹1,500–₹2,500"],["TOTAL","₹3,500–₹6,000","₹6,000–₹11,000"]].map(([cat,...vals])=><tr key={cat} className="bg-white hover:bg-parchment/40 transition-colors"><td className="p-3.5 text-xs text-ink font-medium">{cat}</td>{vals.map((v,i)=><td key={i} className="p-3.5 text-xs text-muted font-light text-center">{v}</td>)}</tr>)}</tbody></table>
          </div>
        </section>

        <AffiliateBlock destination="Hampi Karnataka" hotels={[{name:"Evolve Back Hampi",type:"Luxury · Heritage resort",price:"From ₹15,000/night",rating:"5",badge:"Most luxurious",url:"https://www.booking.com/hotel/in/evolve-back-hampi.html?aid=YOUR_AFFILIATE_ID"},{name:"Mowgli Guest House",type:"Hippie Island · Riverside",price:"From ₹500/night",rating:"3",badge:"Best budget island",url:"https://www.booking.com/hotel/in/mowgli-guest-house-hampi.html?aid=YOUR_AFFILIATE_ID"},{name:"Hotel Mayura Bhuvaneshwari",type:"KSTDC · Hampi side",price:"From ₹1,500/night",rating:"3",badge:"Best location",url:"https://www.booking.com/hotel/in/mayura-bhuvaneshwari-hampi.html?aid=YOUR_AFFILIATE_ID"},{name:"Hampi's Boulders",type:"Boutique · Hippie Island",price:"From ₹6,000/night",rating:"4",badge:"Unique stay",url:"https://www.booking.com/hotel/in/hampis-boulders.html?aid=YOUR_AFFILIATE_ID"}]} activities={[{name:"Hampi Full Day Guided Tour",duration:"8hrs",price:"From ₹1,200/person",badge:"Must do",url:"https://www.getyourguide.com/hampi-l3012/?partner_id=PSZA5UI"},{name:"Hampi Coracle Ride + Ruins",duration:"3hrs",price:"From ₹500/person",badge:"Iconic",url:"https://www.getyourguide.com/hampi-l3012/?partner_id=PSZA5UI"},{name:"Boulder Scramble + Sunrise Trek",duration:"2hrs",price:"From ₹300/person",url:"https://www.getyourguide.com/hampi-l3012/?partner_id=PSZA5UI"},{name:"Hampi Photography Tour",duration:"4hrs",price:"From ₹800/person",url:"https://www.getyourguide.com/hampi-l3012/?partner_id=PSZA5UI"}]}/>

        <DestinationGallery title="Hampi — Ancient Ruins & Boulders" subtitle="The Vijayanagara Empire's sprawling, surreal legacy." spots={[{name:"Vittala Temple Stone Chariot",query:"vittala temple stone chariot hampi karnataka ruins",desc:"The stone chariot in front of Vittala Temple — the iconic image of Hampi."},{name:"Hampi Boulders",query:"hampi boulders granite rocks karnataka ruins landscape",desc:"Giant granite boulders stacked in impossible formations across 26 square kilometres."},{name:"Tungabhadra River",query:"tungabhadra river hampi coracle ruins sunset karnataka",desc:"The Tungabhadra at Hampi — coracle rides at sunset with ruins in the background."},{name:"Virupaksha Temple",query:"virupaksha temple hampi gopuram karnataka ancient",desc:"The 1,200-year continuously functioning temple — the tallest gopuram in Hampi."},{name:"Hampi Ruins Landscape",query:"hampi ruins landscape vijayanagara karnataka ancient empire",desc:"The scale of the Vijayanagara ruins — temples scattered across kilometres of boulder landscape."}]}/>

        <section id="tips" className="mb-14">
          <h2 className="font-serif text-[1.9rem] font-light text-ink mb-6">💡 Pro Tips</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
            {[{i:"🚲",t:"Rent a bicycle, not an auto",d:"Auto tours of Hampi skip the best things — the small temples between main sites, boulder scrambles, quiet river spots. Bicycle lets you stop anywhere. Rs.100–Rs.150/day.",c:"bg-amber-50 border-amber-200"},{i:"🌅",t:"Matanga Hill at sunrise (5:30am)",d:"The view of Hampi from Matanga Hill at dawn — ruins in every direction, boulders turning gold, Tungabhadra gleaming — is the best sunrise view in Karnataka. It's a 30-minute climb. Worth the alarm. I've overslept and missed it twice; don't be me.",c:"bg-orange-50 border-orange-200"},{i:"🏛️",t:"Vittala Temple at 6:30am opening",d:"Vittala Temple is Hampi's most visited site. By 10am it's packed. At 6:30am opening you can have the stone chariot and musical pillars almost completely to yourself for 45 minutes.",c:"bg-blue-50 border-blue-200"},{i:"🤝",t:"Hire a guide for half a day only",d:"A knowledgeable guide for the Vittala–Royal Enclosure circuit is worth it (Rs.500–Rs.800, 3–4hrs). The rest of Hampi you can explore independently — the ruins are well-labelled.",c:"bg-green-50 border-green-200"},{i:"💧",t:"Carry 2L water minimum",d:"Hampi is in a semi-arid zone. The granite boulders reflect and concentrate heat. Between October and April you lose water extremely fast. Carry at least 2L and refill at the entrance gates.",c:"bg-teal-50 border-teal-200"},{i:"🌙",t:"Hippie Island for sunsets",d:"The hippie island (Virupapur Gadde) has the best sunset cafes — Laughing Buddha has rooftop seating with boulders and ruins in every direction. Far better than the tourist restaurants in Hampi Bazaar.",c:"bg-purple-50 border-purple-200"}].map(t=><div key={t.t} className={`rounded-xl p-4 border ${t.c}`}><div className="flex items-start gap-3"><span className="text-xl flex-shrink-0">{t.i}</span><div><p className="font-medium text-sm text-ink mb-1">{t.t}</p><p className="text-xs text-muted font-light leading-relaxed">{t.d}</p></div></div></div>)}
          </div>
        </section>

        <div className="mb-14 bg-ink rounded-2xl p-8 text-center">
          <span className="text-[0.65rem] tracking-[0.2em] uppercase text-gold block mb-3">Free Service</span>
          <h2 className="font-serif text-[1.9rem] font-light text-white mb-3">Want Your Hampi Trip Planned?</h2>
          <p className="text-sm text-white/55 font-light mb-7 max-w-[380px] mx-auto leading-relaxed">Tell us your dates — personalised Hampi itinerary in 24 hours. Free.</p>
          <button onClick={()=>setM(true)} className="btn-gold">Plan My Trip →</button>
        </div>

        <section id="faq" className="mb-14">
          <h2 className="font-serif text-[1.9rem] font-light text-ink mb-6">❓ FAQ</h2>
          <div className="space-y-3">
            {[{q:"How to reach Hampi from Bangalore?",a:"Train to Hosapete Junction (7–8hrs, Rs.200–Rs.600) then auto to Hampi (Rs.200–Rs.300, 20mins). Overnight bus direct to Hosapete (8hrs, Rs.400–Rs.900)."},{q:"Best time to visit Hampi?",a:"October to February. Cool 20–28°C, comfortable for exploring ruins all day. Avoid May–June (40°C+ unbearable)."},{q:"Is Hampi safe for solo female travellers?",a:"Yes — Hampi is very safe. Hippie Island is particularly relaxed and international. Basic precautions apply: don't trek boulders alone at night, keep valuables secured."},{q:"How much does Hampi cost?",a:"Rs.3,500–Rs.6,000 per person for 3 days (as of early 2026) including transport from Bangalore, budget accommodation, bicycle and entry fees."},{q:"What is the Vittala Temple stone chariot?",a:"A stone temple-chariot (ratha) carved in the 16th century — originally with wooden wheels that actually rotated. The chariot was used as a lighthouse on the river. It's the iconic image of Hampi and one of the most-photographed objects in India."}].map((item,i)=><FAQ key={i} {...item}/>)}
          </div>
        </section>
        <Comments/>
        <section className="mt-14"><h3 className="font-serif text-lg font-light text-ink mb-4">More South India Guides</h3>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">{[{label:"Coorg 3 Days — Coffee Estates",href:"/blog/coorg-3-days"},{label:"Kerala 5 Days — Backwaters",href:"/blog/kerala-5-days"},{label:"Goa 3 Days — Beaches",href:"/blog/goa-3-days"},{label:"Golden Triangle 7 Days",href:"/blog/golden-triangle-7-days"}].map(link=><Link key={link.label} href={link.href} className="flex items-center justify-between p-4 bg-white rounded-lg border border-parchment-2 hover:border-gold hover:shadow-sm transition-all duration-200 group"><span className="text-sm text-ink font-light group-hover:text-teal transition-colors">{link.label}</span><span className="text-xs text-muted">Read →</span></Link>)}</div>
        </section>
        <RelatedGuides currentSlug="hampi-3-days" />
      </div>
    </main>
    <Footer/><InquiryModal isOpen={m} onClose={()=>setM(false)}/>
  </>;
}
